# Generated by dtolator --from-openapi test-ref-description.json --pydantic
# Do not modify manually

from pydantic import BaseModel, Field

class Address(BaseModel):
    street: str
    city: str

class ContactInfo(BaseModel):
    email: str
    phone: str | None = None

class Person(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str = Field(description="Full name of the person")
    home_address: Address = Field(alias="homeAddress", description="Primary residential address")
    work_address: Address | None = Field(None, alias="workAddress")
    contact: ContactInfo | None = Field(None, description="Contact information if available")
    billing_address: Address | None = Field(None, alias="billingAddress", description="Address used for billing")

