# Generated by dtolator --from-openapi test-ref-description.json --pydantic
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

class Address(BaseModel):
    street: str
    city: str

class ContactInfo(BaseModel):
    email: str
    phone: str | None = None

class Person(BaseModel):
    name: str = Field(description="Full name of the person")
    homeAddress: Address = Field(description="Primary residential address")
    workAddress: Address | None = None
    contact: ContactInfo | None = Field(None, description="Contact information if available")

