// Generated by dtolator --from-json-schema schema.json --zod
// Do not modify manually

import { z } from "zod";
export const FeaturesSchema = z.object({
  advancedReporting: z.boolean(),
  apiAccess: z.boolean(),
  customBranding: z.unknown().nullable(),
});

export type Features = z.infer<typeof FeaturesSchema>;

export const NotificationsSchema = z.object({
  email: z.boolean(),
  push: z.boolean(),
  sms: z.unknown().nullable(),
});

export type Notifications = z.infer<typeof NotificationsSchema>;

export const PasswordPolicySchema = z.object({
  minLength: z.number().int(),
  requireNumbers: z.boolean(),
  requireSpecialChars: z.boolean(),
});

export type PasswordPolicy = z.infer<typeof PasswordPolicySchema>;

export const StatisticsSchema = z.object({
  activeUsers: z.number().int(),
  growth: z.number(),
  totalUsers: z.number().int(),
});

export type Statistics = z.infer<typeof StatisticsSchema>;

export const PreferencesSchema = z.object({
  language: z.string(),
  notifications: NotificationsSchema,
  theme: z.string(),
});

export type Preferences = z.infer<typeof PreferencesSchema>;

export const SecuritySchema = z.object({
  passwordPolicy: PasswordPolicySchema,
  twoFactorRequired: z.boolean(),
});

export type Security = z.infer<typeof SecuritySchema>;

export const MetadataSchema = z.object({
  createdAt: z.string(),
  lastLogin: z.string(),
  preferences: PreferencesSchema,
});

export type Metadata = z.infer<typeof MetadataSchema>;

export const SettingsSchema = z.object({
  features: FeaturesSchema,
  security: SecuritySchema,
});

export type Settings = z.infer<typeof SettingsSchema>;

export const UserSchema = z.object({
  email: z.string(),
  id: z.number().int(),
  metadata: MetadataSchema,
  name: z.string(),
  permissions: z.array(z.string()),
  role: z.string(),
});

export type User = z.infer<typeof UserSchema>;

export const OrganizationSchema = z.object({
  industry: z.string(),
  name: z.string(),
  settings: SettingsSchema,
});

export type Organization = z.infer<typeof OrganizationSchema>;

/** Schema generated from plain JSON input */
export const RootSchema = z.object({
  organization: OrganizationSchema,
  statistics: StatisticsSchema,
  users: z.array(UserSchema),
});

/** Schema generated from plain JSON input */
export type Root = z.infer<typeof RootSchema>;
