# Generated by dtolator --from-json test-data-simple.json --pydantic --pydantic-version 2
# Do not modify manually

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

class ProfileSocialLinks(BaseModel):
    github: str
    twitter: str

class RootAddress(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    street: str
    city: str
    zip_code: str = Field(alias="zipCode")

class Profile(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    bio: str
    avatar: Any | None
    social_links: ProfileSocialLinks = Field(alias="socialLinks")

class Root(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: int
    name: str
    email: str
    is_active: bool = Field(alias="isActive")
    age: int
    address: RootAddress
    tags: list[str]
    profile: Profile

