# Generated by dtolator --from-json test-data-simple.json --pydantic-v2
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

class RootAddress(BaseModel):
    city: str
    street: str
    zipCode: str

class ProfileSocialLinks(BaseModel):
    github: str
    twitter: str

class Profile(BaseModel):
    avatar: Any | None
    bio: str
    socialLinks: ProfileSocialLinks

class Root(BaseModel):
    address: RootAddress
    age: int
    email: str
    id: int
    isActive: bool
    name: str
    profile: Profile
    tags: list[str]


