// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { fillUrl } from './fill-url';
import type {
  ProductAnalytics,
  SalesAnalytics,
  SalesAnalyticsQueryParams,
} from './dto';

@Injectable({ providedIn: 'root' })
export class AnalyticsApi {
  constructor(private http: HttpClient) {}

  /**
   * Get Sales Analytics
   *
   * @param queryParams - Query parameters object
   * @param queryParams.startDate - optional parameter of type string
   * @param queryParams.endDate - optional parameter of type string
   * @param headers - Optional custom HTTP headers
   * @returns Observable<SalesAnalytics> - Sales analytics data
   */
  getSalesAnalytics(queryParams?: SalesAnalyticsQueryParams, headers?: HttpHeaders): Observable<SalesAnalytics> {
    const url = fillUrl('/analytics/sales', {}, queryParams || {});
    return this.http.get<SalesAnalytics>(url, { headers });
  }

  /**
   * Get Product Analytics
   *
   * @param headers - Optional custom HTTP headers
   * @returns Observable<ProductAnalytics> - Product analytics data
   */
  getProductAnalytics(headers?: HttpHeaders): Observable<ProductAnalytics> {
    const url = fillUrl('/analytics/products', {}, {});
    return this.http.get<ProductAnalytics>(url, { headers });
  }

}

