// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  ProductAnalytics,
  SalesAnalytics,
  SalesAnalyticsQueryParams,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class AnalyticsApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Get Sales Analytics
   *
   * @param queryParams - Query parameters object
   * @param queryParams.startDate - optional parameter of type string
   * @param queryParams.endDate - optional parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<SalesAnalytics> - Sales analytics data
   */
  getSalesAnalytics(queryParams?: SalesAnalyticsQueryParams, headers?: HttpHeaders): Observable<SalesAnalytics> {
    const url = `${this.baseUrl}/analytics/sales`;
    return this.http.get<SalesAnalytics>(url, { headers, params: queryParams });
  }

  /**
   * Get Product Analytics
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<ProductAnalytics> - Product analytics data
   */
  getProductAnalytics(headers?: HttpHeaders): Observable<ProductAnalytics> {
    const url = `${this.baseUrl}/analytics/products`;
    return this.http.get<ProductAnalytics>(url, { headers });
  }

}

