// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state?: string | null;
  country: string;
  postalCode: string;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
  parentId?: string | null;
  isActive?: boolean;
}

export interface CreateCategoryRequest {
  name: string;
  slug: string;
  description?: string;
  parentId?: string;
}

export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    details?: {
    field?: string;
    message?: string;
  }[];
    requestId?: string;
    timestamp?: string;
  };
}

export interface ImageUrl {
  url: string;
  alt?: string;
  width?: number;
  height?: number;
}

export interface Inventory {
  quantity: number;
  status: "in_stock" | "low_stock" | "out_of_stock" | "discontinued";
  lowStockThreshold?: number;
}

export interface NotificationSettings {
  email?: boolean;
  push?: boolean;
  sms?: boolean;
  marketing?: boolean;
}

export type OrderStatus =
  | "pending"
  | "confirmed"
  | "processing"
  | "shipped"
  | "delivered"
  | "cancelled"
  | "refunded";

export interface PaginationInfo {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNext?: boolean;
  hasPrev?: boolean;
}

export interface PaymentMethod {
  type: "credit_card" | "debit_card" | "paypal" | "bank_transfer" | "crypto";
  last4?: string;
  brand?: "visa" | "mastercard" | "amex" | "discover";
}

export interface Price {
  amount: number;
  currency: "USD" | "EUR" | "GBP" | "JPY";
  originalAmount?: number | null;
}

export interface ProductAnalytics {
  totalProducts: number;
  activeProducts: number;
  categoryBreakdown?: Record<string, unknown>;
  lowStockProducts?: {
    productId?: string;
    productName?: string;
    currentStock?: number;
    threshold?: number;
  }[];
}

export type ProductCategory =
  | "electronics"
  | "clothing"
  | "home"
  | "books"
  | "sports"
  | "beauty"
  | "automotive";

export interface SalesAnalytics {
  totalRevenue: number;
  totalOrders: number;
  averageOrderValue: number;
  topProducts?: {
    productId?: string;
    productName?: string;
    revenue?: number;
    unitsSold?: number;
  }[];
  period?: {
    startDate?: string;
    endDate?: string;
  };
}

export interface UpdateInventoryRequest {
  quantity: number;
  lowStockThreshold?: number;
}

export type UserRole =
  | "customer"
  | "admin"
  | "moderator"
  | "vendor";

export interface UserProfile {
  firstName: string;
  lastName: string;
  dateOfBirth?: string | null;
  phoneNumber?: string | null;
  avatar?: ImageUrl;
  address?: Address;
}

export interface InventoryResponse {
  data: {
    productId: string;
    productName?: string;
    inventory: Inventory;
  }[];
}

export interface UserPreferences {
  language?: "en" | "es" | "fr" | "de" | "it";
  currency?: "USD" | "EUR" | "GBP" | "JPY";
  notifications?: NotificationSettings;
  theme?: "light" | "dark" | "auto";
}

export interface UpdateOrderStatusRequest {
  status: OrderStatus;
  trackingNumber?: string;
}

export interface CreateOrderRequest {
  items: {
    productId: string;
    quantity: number;
  }[];
  shippingAddress: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
}

export interface Product {
  id: string;
  name: string;
  description?: string | null;
  price: Price;
  category: ProductCategory;
  tags?: string[];
  images?: ImageUrl[];
  inventory?: Inventory;
  specifications?: Record<string, unknown>;
  isActive?: boolean;
  createdAt?: string;
}

export interface UpdateProductRequest {
  name?: string;
  description?: string;
  price?: Price;
  category?: ProductCategory;
  isActive?: boolean;
}

export interface CreateUserRequest {
  email: string;
  password: string;
  profile: UserProfile;
  preferences?: UserPreferences;
}

export interface User {
  id: string;
  email: string;
  profile: UserProfile;
  preferences?: UserPreferences;
  createdAt?: string;
  updatedAt?: string;
  isActive?: boolean;
  roles?: UserRole[];
}

export interface OrderItem {
  productId: string;
  quantity: number;
  price: Price;
  productSnapshot?: Product;
}

export interface ProductListResponse {
  data: Product[];
  pagination: PaginationInfo;
  filters?: {
    categories?: ProductCategory[];
    priceRange?: {
    min?: number;
    max?: number;
  };
  };
}

export interface UserListResponse {
  data: User[];
  pagination: PaginationInfo;
}

export interface Order {
  id: string;
  userId: string;
  items: OrderItem[];
  total: Price;
  status: OrderStatus;
  shippingAddress?: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
  orderDate?: string;
  estimatedDelivery?: string | null;
  trackingNumber?: string | null;
}


/**
 * Query parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationQueryParams {
  page?: number;
  limit?: number;
}

/**
 * Query parameters for Search Products With Filters
 */
export interface SearchProductsWithFiltersQueryParams {
  category?: ProductCategory;
  minPrice?: number;
  maxPrice?: number;
}

/**
 * Query parameters for Get Inventory Levels
 */
export interface InventoryLevelsQueryParams {
  lowStock?: boolean;
}

/**
 * Query parameters for Get Sales Analytics
 */
export interface SalesAnalyticsQueryParams {
  startDate?: string;
  endDate?: string;
}

