// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

/** Physical mailing or shipping address */
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state?: string | null;
  /** ISO 3166-1 alpha-2 country code */
  country: string;
  postalCode: string;
}

/** Product category with optional hierarchy */
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
  parentId?: string | null;
  isActive?: boolean;
}

/** Request body for creating a new category */
export interface CreateCategoryRequest {
  name: string;
  slug: string;
  description?: string;
  parentId?: string;
}

/** Standard error response envelope */
export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    details?: {
    field?: string;
    message?: string;
  }[];
    requestId?: string;
    timestamp?: string;
  };
}

/** Image with URL and optional metadata */
export interface ImageUrl {
  /** Image URL */
  url: string;
  /** Alternative text for the image */
  alt?: string;
  width?: number;
  height?: number;
}

/** Stock level and availability for a product */
export interface Inventory {
  quantity: number;
  status: "in_stock" | "low_stock" | "out_of_stock" | "discontinued";
  lowStockThreshold?: number;
}

/** Per-channel notification opt-in settings */
export interface NotificationSettings {
  email?: boolean;
  push?: boolean;
  sms?: boolean;
  marketing?: boolean;
}

/** Current lifecycle status of an order */
export type OrderStatus =
  | "pending"
  | "confirmed"
  | "processing"
  | "shipped"
  | "delivered"
  | "cancelled"
  | "refunded";

/** Pagination metadata for list responses */
export interface PaginationInfo {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNext?: boolean;
  hasPrev?: boolean;
}

/** Payment instrument used for an order */
export interface PaymentMethod {
  type: "credit_card" | "debit_card" | "paypal" | "bank_transfer" | "crypto";
  /** Last 4 digits of card (for card payments) */
  last4?: string;
  /** Card brand (for card payments) */
  brand?: "visa" | "mastercard" | "amex" | "discover";
}

/** Monetary amount with currency */
export interface Price {
  amount: number;
  currency: "USD" | "EUR" | "GBP" | "JPY";
  /** Original price before discount */
  originalAmount?: number | null;
}

/** Catalog statistics and stock health metrics */
export interface ProductAnalytics {
  totalProducts: number;
  activeProducts: number;
  categoryBreakdown?: Record<string, number>;
  lowStockProducts?: {
    productId?: string;
    productName?: string;
    currentStock?: number;
    threshold?: number;
  }[];
}

/** Top-level product category */
export type ProductCategory =
  | "electronics"
  | "clothing"
  | "home"
  | "books"
  | "sports"
  | "beauty"
  | "automotive";

/** Aggregated sales metrics for a given period */
export interface SalesAnalytics {
  totalRevenue: number;
  totalOrders: number;
  averageOrderValue: number;
  topProducts?: {
    productId?: string;
    productName?: string;
    revenue?: number;
    unitsSold?: number;
  }[];
  period?: {
    startDate?: string;
    endDate?: string;
  };
}

/** Request body for updating product inventory */
export interface UpdateInventoryRequest {
  quantity: number;
  lowStockThreshold?: number;
}

/** Role assigned to a user account */
export type UserRole =
  | "customer"
  | "admin"
  | "moderator"
  | "vendor";

/** Personal profile information for a user */
export interface UserProfile {
  firstName: string;
  lastName: string;
  dateOfBirth?: string | null;
  phoneNumber?: string | null;
  avatar?: ImageUrl;
  address?: Address;
}

/** Inventory levels for a list of products */
export interface InventoryResponse {
  data: {
    productId: string;
    productName?: string;
    inventory: Inventory;
  }[];
}

/** User-configurable application preferences */
export interface UserPreferences {
  language?: "en" | "es" | "fr" | "de" | "it";
  currency?: "USD" | "EUR" | "GBP" | "JPY";
  notifications?: NotificationSettings;
  theme?: "light" | "dark" | "auto";
}

/** Request body for updating an order's status */
export interface UpdateOrderStatusRequest {
  status: OrderStatus;
  trackingNumber?: string;
}

/** Request body for placing a new order */
export interface CreateOrderRequest {
  items: {
    productId: string;
    quantity: number;
  }[];
  shippingAddress: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
}

/** A product listed in the catalog */
export interface Product {
  id: string;
  name: string;
  description?: string | null;
  price: Price;
  category: ProductCategory;
  tags?: string[];
  images?: ImageUrl[];
  inventory?: Inventory;
  specifications?: Record<string, string | number | boolean>;
  isActive?: boolean;
  createdAt?: string;
}

/** Request body for partially updating a product */
export interface UpdateProductRequest {
  name?: string;
  description?: string;
  price?: Price;
  category?: ProductCategory;
  isActive?: boolean;
}

/** Request body for creating a new user account */
export interface CreateUserRequest {
  email: string;
  password: string;
  profile: UserProfile;
  preferences?: UserPreferences;
}

/** Registered user account */
export interface User {
  /** Unique user identifier */
  id: string;
  /** User's email address */
  email: string;
  profile: UserProfile;
  preferences?: UserPreferences;
  createdAt?: string;
  updatedAt?: string;
  isActive?: boolean;
  roles?: UserRole[];
}

/** A single line item within an order */
export interface OrderItem {
  productId: string;
  quantity: number;
  price: Price;
  productSnapshot?: Product;
}

/** Paginated list of products with optional filters */
export interface ProductListResponse {
  data: Product[];
  pagination: PaginationInfo;
  filters?: {
    categories?: ProductCategory[];
    priceRange?: {
    min?: number;
    max?: number;
  };
  };
}

/** Paginated list of users */
export interface UserListResponse {
  data: User[];
  pagination: PaginationInfo;
}

/** A customer purchase order */
export interface Order {
  id: string;
  userId: string;
  items: OrderItem[];
  total: Price;
  status: OrderStatus;
  shippingAddress?: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
  orderDate?: string;
  estimatedDelivery?: string | null;
  trackingNumber?: string | null;
}

/**
 * Query parameters for Get All Users With Pagination
 */
export type AllUsersWithPaginationQueryParams = Partial<{
  page: number;
  limit: number;
}>;

/**
 * Query parameters for Search Products With Filters
 */
export type SearchProductsWithFiltersQueryParams = Partial<{
  category: ProductCategory;
  minPrice: number;
  maxPrice: number;
}>;

/**
 * Query parameters for Get Inventory Levels
 */
export type InventoryLevelsQueryParams = Partial<{
  lowStock: boolean;
}>;

/**
 * Query parameters for Get Sales Analytics
 */
export type SalesAnalyticsQueryParams = Partial<{
  startDate: string;
  endDate: string;
}>;


/**
 * Header parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationHeaders {
  "X-API-Key"?: string;
}

