// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { fillUrl } from './fill-url';
import {
  CreateOrderRequest,
  Order,
  UpdateOrderStatusRequest,
} from './dto';

@Injectable({ providedIn: 'root' })
export class OrdersApi {
  constructor(private http: HttpClient) {}

  /**
   * Create New Order
   *
   * @param dto - Request body of type CreateOrderRequest
   * @param headers - Optional custom HTTP headers
   * @returns Observable<Order> - Order created
   */
  createNewOrder(dto: CreateOrderRequest, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders', {}, {});
    return this.http.post<Order>(url, dto, { headers });
  }

  /**
   * Get Order By ID
   *
   * @param orderId - Path parameter of type string
   * @param headers - Optional custom HTTP headers
   * @returns Observable<Order> - Order found
   */
  getOrderByID(orderId: string, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders/{orderId}', { orderId: orderId }, {});
    return this.http.get<Order>(url, { headers });
  }

  /**
   * Update Order Status
   *
   * @param orderId - Path parameter of type string
   * @param dto - Request body of type UpdateOrderStatusRequest
   * @param headers - Optional custom HTTP headers
   * @returns Observable<Order> - Order status updated
   */
  updateOrderStatus(orderId: string, dto: UpdateOrderStatusRequest, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders/{orderId}', { orderId: orderId }, {});
    return this.http.patch<Order>(url, dto, { headers });
  }

}

