// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  CreateOrderRequest,
  Order,
  UpdateOrderStatusRequest,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class OrdersApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Create New Order
   *
   * @param dto - Request body of type CreateOrderRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order created
   */
  createNewOrder(dto: CreateOrderRequest, headers?: HttpHeaders): Observable<Order> {
    const url = `${this.baseUrl}/orders`;
    return this.http.post<Order>(url, dto, { headers });
  }

  /**
   * Get Order By ID
   *
   * @param orderId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order found
   */
  getOrderByID(orderId: string, headers?: HttpHeaders): Observable<Order> {
    const url = `${this.baseUrl}/orders/${encodeURIComponent(orderId)}`;
    return this.http.get<Order>(url, { headers });
  }

  /**
   * Update Order Status
   *
   * @param orderId - Path parameter of type string
   * @param dto - Request body of type UpdateOrderStatusRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order status updated
   */
  updateOrderStatus(orderId: string, dto: UpdateOrderStatusRequest, headers?: HttpHeaders): Observable<Order> {
    const url = `${this.baseUrl}/orders/${encodeURIComponent(orderId)}`;
    return this.http.patch<Order>(url, dto, { headers });
  }

}

