// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  Product,
  ProductListResponse,
  SearchProductsWithFiltersQueryParams,
  UpdateProductRequest,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class ProductsApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Search Products With Filters
   *
   * @param queryParams - Query parameters object
   * @param queryParams.category - optional parameter of type ProductCategory
   * @param queryParams.minPrice - optional parameter of type number
   * @param queryParams.maxPrice - optional parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Observable<ProductListResponse> - Products list
   */
  searchProductsWithFilters(queryParams?: SearchProductsWithFiltersQueryParams, headers?: HttpHeaders): Observable<ProductListResponse> {
    const url = `${this.baseUrl}/products`;
    return this.http.get<ProductListResponse>(url, { headers, params: queryParams });
  }

  /**
   * Get Product By ID
   *
   * @param productId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<Product> - Product found
   */
  getProductByID(productId: string, headers?: HttpHeaders): Observable<Product> {
    const url = `${this.baseUrl}/products/${encodeURIComponent(productId)}`;
    return this.http.get<Product>(url, { headers });
  }

  /**
   * Update Product
   *
   * @param productId - Path parameter of type string
   * @param dto - Request body of type UpdateProductRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Product> - Product updated
   */
  updateProduct(productId: string, dto: UpdateProductRequest, headers?: HttpHeaders): Observable<Product> {
    const url = `${this.baseUrl}/products/${encodeURIComponent(productId)}`;
    return this.http.put<Product>(url, dto, { headers });
  }

}

