// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable } from "@angular/core";
import type { Observable } from "rxjs";
import { fillUrl } from "./fill-url";
import type {
  Product,
  ProductCategory,
  ProductListResponse,
  SearchProductsWithFiltersQueryParams,
  UpdateProductRequest,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class ProductsApi {
  constructor(private http: HttpClient) {}

  /**
   * Search Products With Filters
   *
   * @param queryParams - Query parameters object
   * @param queryParams.category - optional parameter of type ProductCategory
   * @param queryParams.minPrice - optional parameter of type number
   * @param queryParams.maxPrice - optional parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Observable<ProductListResponse> - Products list
   */
  searchProductsWithFilters(queryParams?: SearchProductsWithFiltersQueryParams, headers?: HttpHeaders): Observable<ProductListResponse> {
    const url = fillUrl('/products', {}, queryParams || {});
    return this.http.get<ProductListResponse>(url, { headers });
  }

  /**
   * Get Product By ID
   *
   * @param productId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<Product> - Product found
   */
  getProductByID(productId: string, headers?: HttpHeaders): Observable<Product> {
    const url = fillUrl('/products/{productId}', { productId: productId }, {});
    return this.http.get<Product>(url, { headers });
  }

  /**
   * Update Product
   *
   * @param productId - Path parameter of type string
   * @param dto - Request body of type UpdateProductRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Product> - Product updated
   */
  updateProduct(productId: string, dto: UpdateProductRequest, headers?: HttpHeaders): Observable<Product> {
    const url = fillUrl('/products/{productId}', { productId: productId }, {});
    return this.http.put<Product>(url, dto, { headers });
  }

}

