// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

export function subsToUrl<T extends Record<string, any> = Record<string, string | number | boolean | null | undefined>>(
  url: string,
  params?: { [key: string]: string | number | boolean | null | undefined; },
  queryParams?: T,
): string {
  if (params) {
    for (const key in params) {
      if (params.hasOwnProperty(key)) {
        const regex = new RegExp(":" + key + "($|/)");
        url = url.replace(regex, params[key] + "$1");
      }
    }
  }

  if (queryParams) {
    const qs = Object.keys(queryParams)
      .filter((key) =>
        queryParams[key] !== null && queryParams[key] !== undefined
      )
      .map((key) => {
        const value = encodeURIComponent(queryParams[key]!);
        return `${key}=${value}`;
      })
      .join("&");

    if (qs.length > 0) {
      url += "?" + qs;
    }
  }

  const injectedApiConfig = (window as any).API_URL;
  if (!injectedApiConfig) {
    throw new Error(
      'API_URL is not configured. Please set (window as any).API_URL to your backend API base URL. Example: (window as any).API_URL = \'https://api.example.com\';'
    );
  }

  return injectedApiConfig + url;
}
