// Generated by dtolator --from-openapi full-sample.json --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  AllUsersWithPaginationHeaders,
  AllUsersWithPaginationQueryParams,
  CreateUserRequest,
  User,
  UserListResponse,
} from "./dto";
import { fillUrl } from "./fill-url";

@Injectable({ providedIn: 'root' })
export class UsersApi {
  constructor(private http: HttpClient) {}

  /**
   * Get All Users With Pagination
   *
   * Retrieve a paginated list of users
   *
   * @param queryParams - Query parameters object
   * @param queryParams.page - optional parameter of type number
   * @param queryParams.limit - optional parameter of type number
   * @param headers - Custom header values or HttpHeaders instance
   * @param headers.X-API-Key - optional header of type string
   * @returns Observable<UserListResponse> - Successful response
   */
  getAllUsersWithPagination(queryParams?: AllUsersWithPaginationQueryParams, headers?: AllUsersWithPaginationHeaders & Record<string, string>): Observable<UserListResponse> {
    const url = fillUrl('/users', {});
    return this.http.get<UserListResponse>(url, { headers, params: queryParams });
  }

  /**
   * Create New User Account
   *
   * Create a new user account
   *
   * @param dto - Request body of type CreateUserRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<User> - User created successfully
   */
  createNewUserAccount(dto: CreateUserRequest, headers?: HttpHeaders): Observable<User> {
    const url = fillUrl('/users', {});
    return this.http.post<User>(url, dto, { headers });
  }

  /**
   * Get User Profile By ID
   *
   * @param userId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<User> - User found
   */
  getUserProfileByID(userId: string, headers?: HttpHeaders): Observable<User> {
    const url = fillUrl('/users/{userId}', { userId: userId });
    return this.http.get<User>(url, { headers });
  }

}

