// Generated by dtolator --from-openapi full-sample.json --angular --separate-models
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  Inventory,
  InventoryLevelsQueryParams,
  InventoryResponse,
  UpdateInventoryRequest,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class InventoryApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Get Inventory Levels
   *
   * @param queryParams - Query parameters object
   * @param queryParams.lowStock - optional parameter of type boolean
   * @param headers - Optional HTTP headers
   * @returns Observable<InventoryResponse> - Inventory levels
   */
  getInventoryLevels(queryParams?: InventoryLevelsQueryParams, headers?: HttpHeaders): Observable<InventoryResponse> {
    const url = `${this.baseUrl}/inventory`;
    return this.http.get<InventoryResponse>(url, { headers, params: queryParams });
  }

  /**
   * Update Product Inventory
   *
   * @param productId - Path parameter of type string
   * @param dto - Request body of type UpdateInventoryRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Inventory> - Inventory updated
   */
  updateProductInventory(productId: string, dto: UpdateInventoryRequest, headers?: HttpHeaders): Observable<Inventory> {
    const url = `${this.baseUrl}/inventory/${encodeURIComponent(productId)}`;
    return this.http.put<Inventory>(url, dto, { headers });
  }

}

