# Generated by dtolator --from-openapi simple-sample.json --pydantic
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

class User(BaseModel):
    id: int
    email: EmailStr = Field(description="The user's primary email address.
Must be unique across the system.
Used for login and notifications.")
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    isActive: bool | None = None
    tags: list[str] | None = None
    status: Literal["active", "inactive", "pending"] | None = None
    profile: UserProfile | None = None
    address: Address | None = None

class UserProfile(BaseModel):
    firstName: str = Field(min_length=1, max_length=50)
    lastName: str = Field(min_length=1, max_length=50)
    phoneNumber: str | None = Field(None, regex=r"^\+?[1-9]\d{1,14}$")
    avatar: HttpUrl | None = None
    bio: str | None = Field(None, max_length=500)

class Address(BaseModel):
    street: str = Field(min_length=1, max_length=100)
    city: str = Field(min_length=1, max_length=50)
    state: str | None = Field(None, max_length=50)
    country: str = Field(regex=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code")
    postalCode: str | None = Field(None, min_length=3, max_length=10)

class CreateUserRequest(BaseModel):
    email: EmailStr
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    profile: UserProfile
    address: Address | None = None

class ApiResponse(BaseModel):
    success: bool
    message: str | None = None
    data: User | None = None

