// Generated by dtolator --from-openapi simple-sample.json --zod --angular --promises
// Do not modify manually

import {
  AddressSchema,
  ApiResponseSchema,
  UserProfileSchema,
  UserSchema,
} from "./schema";
import type { Address, ApiResponse, User, UserProfile } from "./schema";

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}

export type { User };
export type { UserProfile };
export type { Address };
export type { ApiResponse };

export { UserSchema };
export { UserProfileSchema };
export { AddressSchema };
export { ApiResponseSchema };
