// Generated by dtolator --from-openapi simple-sample.json --zod --angular --promises
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import { lastValueFrom } from "rxjs";
import { map } from "rxjs/operators";
import { z } from "zod";

import { ApiResponseSchema, UserSchema } from "./dto";
import type { ApiResponse, CreateUserRequest, User } from "./dto";

@Injectable({ providedIn: 'root' })
export class UsersApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * List All Users
   *
   * Retrieve a list of all users in the system
   *
   * @param headers - Optional HTTP headers
   * @returns Promise<User[]> - Successful response
   */
  listAllUsers(headers?: HttpHeaders): Promise<User[]> {
    const url = `${this.baseUrl}/users`;
    return lastValueFrom(this.http.get<User[]>(url, { headers })
      .pipe(
        map(response => z.array(UserSchema).parse(response))
      ));
  }

  /**
   * Create New User
   *
   * Create a new user account
   *
   * @param dto - Request body of type CreateUserRequest
   * @param headers - Optional HTTP headers
   * @returns Promise<ApiResponse> - User created successfully
   */
  createNewUser(dto: CreateUserRequest, headers?: HttpHeaders): Promise<ApiResponse> {
    const url = `${this.baseUrl}/users`;
    return lastValueFrom(this.http.post<ApiResponse>(url, dto, { headers })
      .pipe(
        map(response => ApiResponseSchema.parse(response))
      ));
  }

  /**
   * Get User By ID
   *
   * Retrieve a specific user by their ID
   *
   * @param userId - Path parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Promise<User> - User found
   */
  getUserById(userId: number, headers?: HttpHeaders): Promise<User> {
    const url = `${this.baseUrl}/users/${encodeURIComponent(userId)}`;
    return lastValueFrom(this.http.get<User>(url, { headers })
      .pipe(
        map(response => UserSchema.parse(response))
      ));
  }

  /**
   * Update User Profile
   *
   * Update an existing user's information
   *
   * @param userId - Path parameter of type number
   * @param dto - Request body of type CreateUserRequest
   * @param headers - Optional HTTP headers
   * @returns Promise<ApiResponse> - User updated successfully
   */
  updateUserProfile(userId: number, dto: CreateUserRequest, headers?: HttpHeaders): Promise<ApiResponse> {
    const url = `${this.baseUrl}/users/${encodeURIComponent(userId)}`;
    return lastValueFrom(this.http.put<ApiResponse>(url, dto, { headers })
      .pipe(
        map(response => ApiResponseSchema.parse(response))
      ));
  }

  /**
   * Delete User Account
   *
   * Permanently delete a user account
   *
   * @param userId - Path parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Promise<ApiResponse> - User deleted successfully
   */
  deleteUserAccount(userId: number, headers?: HttpHeaders): Promise<ApiResponse> {
    const url = `${this.baseUrl}/users/${encodeURIComponent(userId)}`;
    return lastValueFrom(this.http.delete<ApiResponse>(url, { headers })
      .pipe(
        map(response => ApiResponseSchema.parse(response))
      ));
  }

  /**
   * Activate User Account
   *
   * Activate a user's account status
   *
   * @param userId - Path parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Promise<ApiResponse> - User activated successfully
   */
  activateUserAccount(userId: number, headers?: HttpHeaders): Promise<ApiResponse> {
    const url = `${this.baseUrl}/users/${encodeURIComponent(userId)}/activate`;
    return lastValueFrom(this.http.post<ApiResponse>(url, null, { headers })
      .pipe(
        map(response => ApiResponseSchema.parse(response))
      ));
  }

  /**
   * Deactivate User Account
   *
   * Deactivate a user's account status
   *
   * @param userId - Path parameter of type number
   * @param headers - Optional HTTP headers
   * @returns Promise<ApiResponse> - User deactivated successfully
   */
  deactivateUserAccount(userId: number, headers?: HttpHeaders): Promise<ApiResponse> {
    const url = `${this.baseUrl}/users/${encodeURIComponent(userId)}/deactivate`;
    return lastValueFrom(this.http.post<ApiResponse>(url, null, { headers })
      .pipe(
        map(response => ApiResponseSchema.parse(response))
      ));
  }

}

