// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { z } from 'zod';
import { fillUrl } from './fill-url';
import type {
  Category,
  CreateCategoryRequest,
} from './dto';
import {
  CategorySchema,
} from './dto';

@Injectable({ providedIn: 'root' })
export class CategoriesApi {
  constructor(private http: HttpClient) {}

  /**
   * Get All Product Categories
   *
   * @param headers - Optional custom HTTP headers
   * @returns Observable<Category[]> - Categories list
   */
  getAllProductCategories(headers?: HttpHeaders): Observable<Category[]> {
    const url = fillUrl('/categories', {}, {});
    return this.http.get<Category[]>(url, { headers })
      .pipe(
        map(response => z.array(CategorySchema).parse(response))
      );
  }

  /**
   * Create New Category
   *
   * @param dto - Request body of type CreateCategoryRequest
   * @param headers - Optional custom HTTP headers
   * @returns Observable<Category> - Category created
   */
  createNewCategory(dto: CreateCategoryRequest, headers?: HttpHeaders): Observable<Category> {
    const url = fillUrl('/categories', {}, {});
    return this.http.post<Category>(url, dto, { headers })
      .pipe(
        map(response => CategorySchema.parse(response))
      );
  }

}

