// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { z } from "zod";

import { CategorySchema } from "./dto";
import type { Category, CreateCategoryRequest } from "./dto";

@Injectable({ providedIn: 'root' })
export class CategoriesApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Get All Product Categories
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<Category[]> - Categories list
   */
  getAllProductCategories(headers?: HttpHeaders): Observable<Category[]> {
    const url = `${this.baseUrl}/categories`;
    return this.http.get<Category[]>(url, { headers })
      .pipe(
        map(response => z.array(CategorySchema).parse(response))
      );
  }

  /**
   * Create New Category
   *
   * @param dto - Request body of type CreateCategoryRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Category> - Category created
   */
  createNewCategory(dto: CreateCategoryRequest, headers?: HttpHeaders): Observable<Category> {
    const url = `${this.baseUrl}/categories`;
    return this.http.post<Category>(url, dto, { headers })
      .pipe(
        map(response => CategorySchema.parse(response))
      );
  }

}

