// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import type { ProductCategory } from "./schema";

/**
 * Query parameters for Get All Users With Pagination
 */
export type AllUsersWithPaginationQueryParams = Partial<{
  page: number;
  limit: number;
}>;

/**
 * Query parameters for Search Products With Filters
 */
export type SearchProductsWithFiltersQueryParams = Partial<{
  category: ProductCategory;
  minPrice: number;
  maxPrice: number;
}>;

/**
 * Query parameters for Get Inventory Levels
 */
export type InventoryLevelsQueryParams = Partial<{
  lowStock: boolean;
}>;

/**
 * Query parameters for Get Sales Analytics
 */
export type SalesAnalyticsQueryParams = Partial<{
  startDate: string;
  endDate: string;
}>;

/**
 * Header parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationHeaders {
  "X-API-Key"?: string;
}

