# Generated by dtolator --from-json-schema schema.json --pydantic
# Do not modify manually

from typing import Any

from pydantic import BaseModel, EmailStr, Field, HttpUrl

class Address(BaseModel):
    """
    A physical mailing address.

    All addresses must include at least `street`, `city`, and `country`.
    The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
    """
    class Config:
        allow_population_by_field_name = True

    city: str = Field(min_length=1, max_length=50)
    country: str = Field(regex=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code")
    postal_code: str | None = Field(None, alias="postalCode", min_length=3, max_length=10)
    state: str | None = Field(None, max_length=50)
    street: str = Field(min_length=1, max_length=100)

class UserProfile(BaseModel):
    class Config:
        allow_population_by_field_name = True

    avatar: HttpUrl | None = None
    bio: str | None = Field(None, max_length=500)
    first_name: str = Field(alias="firstName", min_length=1, max_length=50)
    last_name: str = Field(alias="lastName", min_length=1, max_length=50)
    phone_number: str | None = Field(None, alias="phoneNumber", regex=r"^\+?[1-9]\d{1,14}$")

class CreateUserRequest(BaseModel):
    address: Address | None = None
    age: int | None = Field(None, ge=0, le=150)
    email: EmailStr
    name: str = Field(min_length=1, max_length=100)
    profile: UserProfile

class User(BaseModel):
    """
    Represents a user in the system.

    A user can be in one of the following states:
    - **active**: The user can log in and use the system.
    - **inactive**: The user account is disabled.
    - **pending**: The user has registered but not yet confirmed their email.

    See also: `UserProfile` for extended profile information.
    """
    class Config:
        allow_population_by_field_name = True

    address: Address | None = None
    age: int | None = Field(None, ge=0, le=150)
    email: EmailStr = Field(description="The user's primary email address.\nMust be unique across the system.\nUsed for login and notifications.")
    id: int
    is_active: bool | None = Field(None, alias="isActive")
    name: str = Field(min_length=1, max_length=100)
    profile: UserProfile | None = None
    status: dict[str, Any] | None = None
    tags: list[str] | None = None

class ApiResponse(BaseModel):
    data: User | None = None
    message: str | None = None
    success: bool

Root = User

