// Generated by dtolator --from-openapi test-nullable-oneof.json --typescript
// Do not modify manually

export interface Address {
  street: string;
  city: string;
}

export type PaginationCursor = string;

export type AnyOfNullable =
  unknown | null
  | Address;

export type NonNullableOneOf =
  PaginationCursor
  | Address;

export type NullableMultiType =
  unknown | null
  | PaginationCursor
  | Address;

export interface PaginatedResponse {
  cursor?: unknown | null | PaginationCursor;
  data: string[];
}
