// Generated by dtolator --from-openapi test-nullable-oneof.json --typescript
// Do not modify manually

export interface Address {
  street: string;
  city: string;
}

/** An opaque cursor for pagination */
export type PaginationCursor = string;

/** An anyOf with null */
export type AnyOfNullable =
  unknown | null
  | Address;

/** A oneOf without null should remain a plain union */
export type NonNullableOneOf =
  PaginationCursor
  | Address;

/** A oneOf with null and multiple non-null types */
export type NullableMultiType =
  unknown | null
  | PaginationCursor
  | Address;

export interface PaginatedResponse {
  cursor?: unknown | null | PaginationCursor;
  data: string[];
}
