// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { z } from 'zod';
import { fillUrl } from './fill-url';
import {
  Category,
  CategorySchema,
  CreateCategoryRequest,
} from './dto';

@Injectable({ providedIn: 'root' })
export class CategoriesApi {
  constructor(private http: HttpClient) {}

  /**
   * Get All Product Categories
   *
   * @returns Observable<Category[]> - Categories list
   */
  getAllProductCategories(): Observable<Category[]> {
    const url = fillUrl('/categories', {}, {});
    return this.http.get<Category[]>(url)
      .pipe(
        map(response => z.array(CategorySchema).parse(response))
      );
  }

  /**
   * Create New Category
   *
   * @param dto - Request body of type CreateCategoryRequest
   * @returns Observable<Category> - Category created
   */
  createNewCategory(dto: CreateCategoryRequest): Observable<Category> {
    const url = fillUrl('/categories', {}, {});
    return this.http.post<Category>(url, dto)
      .pipe(
        map(response => CategorySchema.parse(response))
      );
  }

}

