// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import {
  AddressSchema,
  CategorySchema,
  ErrorResponseSchema,
  ImageUrlSchema,
  InventoryResponseSchema,
  InventorySchema,
  NotificationSettingsSchema,
  OrderItemSchema,
  OrderSchema,
  OrderStatusSchema,
  PaginationInfoSchema,
  PaymentMethodSchema,
  PriceSchema,
  ProductAnalyticsSchema,
  ProductCategorySchema,
  ProductListResponseSchema,
  ProductSchema,
  SalesAnalyticsSchema,
  UserListResponseSchema,
  UserPreferencesSchema,
  UserProfileSchema,
  UserRoleSchema,
  UserSchema,
} from "./schema";
import type {
  Address,
  Category,
  ErrorResponse,
  ImageUrl,
  Inventory,
  InventoryResponse,
  NotificationSettings,
  Order,
  OrderItem,
  OrderStatus,
  PaginationInfo,
  PaymentMethod,
  Price,
  Product,
  ProductAnalytics,
  ProductCategory,
  ProductListResponse,
  SalesAnalytics,
  User,
  UserListResponse,
  UserPreferences,
  UserProfile,
  UserRole,
} from "./schema";

export interface CreateCategoryRequest {
  name: string;
  slug: string;
  description?: string;
  parentId?: string;
}
export interface UpdateInventoryRequest {
  quantity: number;
  lowStockThreshold?: number;
}
export interface UpdateOrderStatusRequest {
  status: OrderStatus;
  trackingNumber?: string;
}
export interface CreateOrderRequest {
  items: {
    productId: string;
    quantity: number;
  }[];
  shippingAddress: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
}
export interface UpdateProductRequest {
  name?: string;
  description?: string;
  price?: Price;
  category?: ProductCategory;
  isActive?: boolean;
}
export interface CreateUserRequest {
  email: string;
  password: string;
  profile: UserProfile;
  preferences?: UserPreferences;
}

/**
 * Query parameters for Get All Users With Pagination
 */
export type AllUsersWithPaginationQueryParams = Partial<{
  page: number;
  limit: number;
}>;

/**
 * Query parameters for Search Products With Filters
 */
export type SearchProductsWithFiltersQueryParams = Partial<{
  category: ProductCategory;
  minPrice: number;
  maxPrice: number;
}>;

/**
 * Query parameters for Get Inventory Levels
 */
export type InventoryLevelsQueryParams = Partial<{
  lowStock: boolean;
}>;

/**
 * Query parameters for Get Sales Analytics
 */
export type SalesAnalyticsQueryParams = Partial<{
  startDate: string;
  endDate: string;
}>;

export {
  AddressSchema,
  CategorySchema,
  ErrorResponseSchema,
  ImageUrlSchema,
  InventoryResponseSchema,
  InventorySchema,
  NotificationSettingsSchema,
  OrderItemSchema,
  OrderSchema,
  OrderStatusSchema,
  PaginationInfoSchema,
  PaymentMethodSchema,
  PriceSchema,
  ProductAnalyticsSchema,
  ProductCategorySchema,
  ProductListResponseSchema,
  ProductSchema,
  SalesAnalyticsSchema,
  UserListResponseSchema,
  UserPreferencesSchema,
  UserProfileSchema,
  UserRoleSchema,
  UserSchema,
} from "./schema";
export type {
  Address,
  Category,
  ErrorResponse,
  ImageUrl,
  Inventory,
  InventoryResponse,
  NotificationSettings,
  Order,
  OrderItem,
  OrderStatus,
  PaginationInfo,
  PaymentMethod,
  Price,
  Product,
  ProductAnalytics,
  ProductCategory,
  ProductListResponse,
  SalesAnalytics,
  User,
  UserListResponse,
  UserPreferences,
  UserProfile,
  UserRole,
} from "./schema";

/**
 * Header parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationHeaders {
  "X-API-Key"?: string;
}

