// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import type {
  Address,
  Category,
  ErrorResponse,
  ImageUrl,
  Inventory,
  InventoryResponse,
  NotificationSettings,
  Order,
  OrderItem,
  OrderStatus,
  PaginationInfo,
  PaymentMethod,
  Price,
  Product,
  ProductAnalytics,
  ProductCategory,
  ProductListResponse,
  SalesAnalytics,
  User,
  UserListResponse,
  UserPreferences,
  UserProfile,
  UserRole,
} from "./schema";
import {
  AddressSchema,
  CategorySchema,
  ErrorResponseSchema,
  ImageUrlSchema,
  InventorySchema,
  InventoryResponseSchema,
  NotificationSettingsSchema,
  OrderSchema,
  OrderItemSchema,
  OrderStatusSchema,
  PaginationInfoSchema,
  PaymentMethodSchema,
  PriceSchema,
  ProductSchema,
  ProductAnalyticsSchema,
  ProductCategorySchema,
  ProductListResponseSchema,
  SalesAnalyticsSchema,
  UserSchema,
  UserListResponseSchema,
  UserPreferencesSchema,
  UserProfileSchema,
  UserRoleSchema,
} from "./schema";

export interface CreateCategoryRequest {
  name: string;
  slug: string;
  description?: string;
  parentId?: string;
}
export interface UpdateInventoryRequest {
  quantity: number;
  lowStockThreshold?: number;
}
export interface UpdateOrderStatusRequest {
  status: OrderStatus;
  trackingNumber?: string;
}
export interface CreateOrderRequest {
  items: {
    productId: string;
    quantity: number;
  }[];
  shippingAddress: Address;
  billingAddress?: Address;
  paymentMethod?: PaymentMethod;
}
export interface UpdateProductRequest {
  name?: string;
  description?: string;
  price?: Price;
  category?: ProductCategory;
  isActive?: boolean;
}
export interface CreateUserRequest {
  email: string;
  password: string;
  profile: UserProfile;
  preferences?: UserPreferences;
}

/**
 * Query parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationQueryParams {
  page?: number;
  limit?: number;
}

/**
 * Query parameters for Search Products With Filters
 */
export interface SearchProductsWithFiltersQueryParams {
  category?: ProductCategory;
  minPrice?: number;
  maxPrice?: number;
}

/**
 * Query parameters for Get Inventory Levels
 */
export interface InventoryLevelsQueryParams {
  lowStock?: boolean;
}

/**
 * Query parameters for Get Sales Analytics
 */
export interface SalesAnalyticsQueryParams {
  startDate?: string;
  endDate?: string;
}

export type { User };
export type { UserProfile };
export type { UserPreferences };
export type { NotificationSettings };
export type { UserRole };
export type { Address };
export type { ImageUrl };
export type { Product };
export type { Price };
export type { ProductCategory };
export type { Inventory };
export type { Order };
export type { OrderItem };
export type { OrderStatus };
export type { PaymentMethod };
export type { UserListResponse };
export type { ProductListResponse };
export type { PaginationInfo };
export type { ErrorResponse };
export type { Category };
export type { InventoryResponse };
export type { SalesAnalytics };
export type { ProductAnalytics };

export { UserSchema };
export { UserProfileSchema };
export { UserPreferencesSchema };
export { NotificationSettingsSchema };
export { UserRoleSchema };
export { AddressSchema };
export { ImageUrlSchema };
export { ProductSchema };
export { PriceSchema };
export { ProductCategorySchema };
export { InventorySchema };
export { OrderSchema };
export { OrderItemSchema };
export { OrderStatusSchema };
export { PaymentMethodSchema };
export { UserListResponseSchema };
export { ProductListResponseSchema };
export { PaginationInfoSchema };
export { ErrorResponseSchema };
export { CategorySchema };
export { InventoryResponseSchema };
export { SalesAnalyticsSchema };
export { ProductAnalyticsSchema };

/**
 * Query parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationQueryParams {
  page?: number;
  limit?: number;
}

/**
 * Query parameters for Search Products With Filters
 */
export interface SearchProductsWithFiltersQueryParams {
  category?: ProductCategory;
  minPrice?: number;
  maxPrice?: number;
}

/**
 * Query parameters for Get Inventory Levels
 */
export interface InventoryLevelsQueryParams {
  lowStock?: boolean;
}

/**
 * Query parameters for Get Sales Analytics
 */
export interface SalesAnalyticsQueryParams {
  startDate?: string;
  endDate?: string;
}


/**
 * Header parameters for Get All Users With Pagination
 */
export interface AllUsersWithPaginationHeaders {
  "X-API-Key"?: string;
}

