// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable } from "@angular/core";
import type { Observable } from "rxjs";
import { map } from "rxjs/operators";

import type {
  Inventory,
  InventoryLevelsQueryParams,
  InventoryResponse,
  UpdateInventoryRequest,
} from "./dto";
import { InventoryResponseSchema, InventorySchema } from "./dto";
import { fillUrl } from "./fill-url";

@Injectable({ providedIn: 'root' })
export class InventoryApi {
  constructor(private http: HttpClient) {}

  /**
   * Get Inventory Levels
   *
   * @param queryParams - Query parameters object
   * @param queryParams.lowStock - optional parameter of type boolean
   * @param headers - Optional HTTP headers
   * @returns Observable<InventoryResponse> - Inventory levels
   */
  getInventoryLevels(queryParams?: InventoryLevelsQueryParams, headers?: HttpHeaders): Observable<InventoryResponse> {
    const url = fillUrl('/inventory', {});
    return this.http.get<InventoryResponse>(url, { headers, params: queryParams })
      .pipe(
        map(response => InventoryResponseSchema.parse(response))
      );
  }

  /**
   * Update Product Inventory
   *
   * @param productId - Path parameter of type string
   * @param dto - Request body of type UpdateInventoryRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Inventory> - Inventory updated
   */
  updateProductInventory(productId: string, dto: UpdateInventoryRequest, headers?: HttpHeaders): Observable<Inventory> {
    const url = fillUrl('/inventory/{productId}', { productId: productId });
    return this.http.put<Inventory>(url, dto, { headers })
      .pipe(
        map(response => InventorySchema.parse(response))
      );
  }

}

