// Generated by dtolator --from-openapi full-sample.json --zod --angular
// Do not modify manually

import type { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable } from "@angular/core";
import type { Observable } from "rxjs";
import { map } from "rxjs/operators";

import { OrderSchema } from "./dto";
import type {
  CreateOrderRequest,
  Order,
  UpdateOrderStatusRequest,
} from "./dto";
import { fillUrl } from "./fill-url";

@Injectable({ providedIn: 'root' })
export class OrdersApi {
  constructor(private http: HttpClient) {}

  /**
   * Create New Order
   *
   * @param dto - Request body of type CreateOrderRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order created
   */
  createNewOrder(dto: CreateOrderRequest, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders', {}, {});
    return this.http.post<Order>(url, dto, { headers })
      .pipe(
        map(response => OrderSchema.parse(response))
      );
  }

  /**
   * Get Order By ID
   *
   * @param orderId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order found
   */
  getOrderByID(orderId: string, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders/{orderId}', { orderId: orderId }, {});
    return this.http.get<Order>(url, { headers })
      .pipe(
        map(response => OrderSchema.parse(response))
      );
  }

  /**
   * Update Order Status
   *
   * @param orderId - Path parameter of type string
   * @param dto - Request body of type UpdateOrderStatusRequest
   * @param headers - Optional HTTP headers
   * @returns Observable<Order> - Order status updated
   */
  updateOrderStatus(orderId: string, dto: UpdateOrderStatusRequest, headers?: HttpHeaders): Observable<Order> {
    const url = fillUrl('/orders/{orderId}', { orderId: orderId }, {});
    return this.http.patch<Order>(url, dto, { headers })
      .pipe(
        map(response => OrderSchema.parse(response))
      );
  }

}

