# Generated by dtolator --json test-output/json-tests/deduplication-test.json --pydantic --pretty
# Do not modify manually

from pydantic import BaseModel, Field
from typing import Optional, Union, List, Dict, Any
from enum import Enum
from datetime import datetime

class Address(BaseModel):
    city: str
    zip: str

class User(BaseModel):
    address: Address

class Root(BaseModel):
    shippingAddress: Address
    billingAddress: Address
    user: User 