// Generated by dtolator --from-openapi test-array-return-import.json --zod --angular
// Do not modify manually

import { ItemSchema } from "./schema";
import type { Item } from "./schema";

export { ItemSchema } from "./schema";
export type { Item } from "./schema";
