// Generated by dtolator --from-openapi test-array-return-import.json --zod --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { z } from "zod";

import { ItemSchema } from "./dto";
import type { Item } from "./dto";

@Injectable({ providedIn: 'root' })
export class ItemsApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * List Items
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<Item[]> - OK
   */
  listItems(headers?: HttpHeaders): Observable<Item[]> {
    const url = `${this.baseUrl}/items`;
    return this.http.get<Item[]>(url, { headers })
      .pipe(
        map(response => z.array(ItemSchema).parse(response))
      );
  }

}

