// Generated by dtolator --from-openapi test-array-return-import.json --zod --angular
// Do not modify manually

import { z } from "zod";
export const ItemSchema = z.object({
  id: z.number().int(),
  name: z.string(),
});

export type Item = z.infer<typeof ItemSchema>;
