// Generated by dtolator --from-openapi test-ref-description.json --zod
// Do not modify manually

import { z } from "zod";
export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
});

export type Address = z.infer<typeof AddressSchema>;

export const ContactInfoSchema = z.object({
  email: z.string(),
  phone: z.string().optional(),
});

export type ContactInfo = z.infer<typeof ContactInfoSchema>;

export const PersonSchema = z.object({
  /** Full name of the person */
  name: z.string(),
  /** Primary residential address */
  homeAddress: AddressSchema,
  workAddress: AddressSchema.optional(),
  /** Contact information if available */
  contact: ContactInfoSchema.nullable().optional(),
  /** Address used for billing */
  billingAddress: AddressSchema.nullable().optional(),
});

export type Person = z.infer<typeof PersonSchema>;
