// Generated by dtolator --from-openapi simple-sample.json --angular --promises
// Do not modify manually

/**
 * A physical mailing address.
 *
 * All addresses must include at least `street`, `city`, and `country`.
 * The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
 */
export interface Address {
  street: string;
  city: string;
  state?: string | null;
  /** ISO 3166-1 alpha-2 country code */
  country: string;
  postalCode?: string | null;
}

export interface UserProfile {
  firstName: string;
  lastName: string;
  phoneNumber?: string | null;
  avatar?: string | null;
  bio?: string | null;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}

/**
 * Represents a user in the system.
 *
 * A user can be in one of the following states:
 * - **active**: The user can log in and use the system.
 * - **inactive**: The user account is disabled.
 * - **pending**: The user has registered but not yet confirmed their email.
 *
 * See also: `UserProfile` for extended profile information.
 */
export interface User {
  id: number;
  /**
   * The user's primary email address.
   * Must be unique across the system.
   * Used for login and notifications.
   */
  email: string;
  name: string;
  age?: number;
  isActive?: boolean;
  tags?: string[];
  status?: "active" | "inactive" | "pending";
  profile?: UserProfile;
  address?: Address;
}

export interface ApiResponse {
  success: boolean;
  message?: string;
  data?: User;
}
