// Generated by dtolator --from-openapi simple-sample.json --angular --promises
// Do not modify manually

export interface Address {
  street: string;
  city: string;
  state?: string | null;
  country: string;
  postalCode?: string | null;
}

export interface UserProfile {
  firstName: string;
  lastName: string;
  phoneNumber?: string | null;
  avatar?: string | null;
  bio?: string | null;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}

export interface User {
  id: number;
  email: string;
  name: string;
  age?: number;
  isActive?: boolean;
  tags?: string[];
  status?: "active" | "inactive" | "pending";
  profile?: UserProfile;
  address?: Address;
}

export interface ApiResponse {
  success: boolean;
  message?: string;
  data?: User;
}
