// Generated by dtolator --json demo-api-response.json --typescript
// Do not modify manually

export interface Item {
  id: string;
  name: string;
  price: number;
  rating: number;
  reviewCount: number;
}

export interface ItemItemSpecifications {
  batteryLife: number;
  brand: string;
  color: string;
  model: string;
  wireless: boolean;
}

export interface PaymentMethod {
  brand: string;
  expiryMonth: number;
  expiryYear: number;
  last4: string;
  type: string;
}

export interface Privacy {
  allowMessages: boolean;
  profileVisible: boolean;
}

export interface ProfilePreferencesNotifications {
  email: boolean;
  push: boolean;
  sms: boolean;
}

export interface RateLimiting {
  limit: number;
  remaining: number;
  resetTime: string;
}

export interface ShippingAddress {
  city: string;
  recipient: string;
  state: string;
  street: string;
  zipCode: string;
}

export interface UserAddressCoordinates {
  latitude: number;
  longitude: number;
}

export interface RecommendationItem {
  item: Item;
  reason: string;
  score: number;
  type: string;
}

export interface ItemItem {
  categories: string[];
  name: string;
  price: number;
  productId: string;
  quantity: number;
  specifications: ItemItemSpecifications;
}

export interface Billing {
  amount: number;
  currency: string;
  interval: string;
  nextBilling: string;
  paymentMethod: PaymentMethod;
}

export interface ProfilePreferences {
  notifications: ProfilePreferencesNotifications;
  privacy: Privacy;
  theme: string;
}

export interface Metadata {
  cached: boolean;
  processingTime: number;
  rateLimiting: RateLimiting;
  requestId: string;
  source: string;
  timestamp: string;
  version: string;
}

export interface Shipping {
  address: ShippingAddress;
  cost: number;
  estimatedDays: number;
  method: string;
  trackingNumber: string;
}

export interface UserAddress {
  city: string;
  coordinates: UserAddressCoordinates;
  country: string;
  state: string;
  street: string;
  zipCode: string;
}

export interface Subscription {
  autoRenew: boolean;
  billing: Billing;
  endDate: string;
  features: string[];
  plan: string;
  startDate: string;
  status: string;
}

export interface Profile {
  age: number;
  avatar: string;
  firstName: string;
  lastName: string;
  preferences: ProfilePreferences;
}

export interface OrderItem {
  currency: string;
  date: string;
  id: string;
  items: {
    categories: string[];
    name: string;
    price: number;
    productId: string;
    quantity: number;
    specifications: ItemItemSpecifications;
  }[];
  shipping: Shipping;
  status: string;
  total: number;
}

export interface User {
  address: UserAddress;
  email: string;
  id: number;
  isActive: boolean;
  orders: {
    currency: string;
    date: string;
    id: string;
    items: {
    categories: string[];
    name: string;
    price: number;
    productId: string;
    quantity: number;
    specifications: ItemItemSpecifications;
  }[];
    shipping: Shipping;
    status: string;
    total: number;
  }[];
  profile: Profile;
  subscription: Subscription;
  username: string;
}

export interface Data {
  recommendations: {
    item: Item;
    reason: string;
    score: number;
    type: string;
  }[];
  user: User;
}

export interface Root {
  data: Data;
  metadata: Metadata;
  status: string;
}

