// Generated by dtolator --from-json test-data-complex.json --typescript
// Do not modify manually

export interface MetadataPreferencesNotifications {
  email: boolean;
  push: boolean;
  sms: unknown | null;
}

export interface OrganizationSettingsFeatures {
  advancedReporting: boolean;
  apiAccess: boolean;
  customBranding: unknown | null;
}

export interface PasswordPolicy {
  minLength: number;
  requireNumbers: boolean;
  requireSpecialChars: boolean;
}

export interface RootStatistics {
  activeUsers: number;
  growth: number;
  totalUsers: number;
}

export interface MetadataPreferences {
  language: string;
  notifications: MetadataPreferencesNotifications;
  theme: string;
}

export interface Security {
  passwordPolicy: PasswordPolicy;
  twoFactorRequired: boolean;
}

export interface Metadata {
  createdAt: string;
  lastLogin: string;
  preferences: MetadataPreferences;
}

export interface OrganizationSettings {
  features: OrganizationSettingsFeatures;
  security: Security;
}

export interface User {
  email: string;
  id: number;
  metadata: Metadata;
  name: string;
  permissions: string[];
  role: string;
}

export interface Organization {
  industry: string;
  name: string;
  settings: OrganizationSettings;
}

export interface Root {
  organization: Organization;
  statistics: RootStatistics;
  users: User[];
}

