// Generated by dtolator --from-json test-data-complex.json --typescript
// Do not modify manually

export interface Root {
  users: User[];
  organization: Organization;
  statistics: RootStatistics;
}

export interface Metadata {
  createdAt: string;
  lastLogin: string;
  preferences: MetadataPreferences;
}

export interface MetadataPreferences {
  theme: string;
  language: string;
  notifications: MetadataPreferencesNotifications;
}

export interface MetadataPreferencesNotifications {
  email: boolean;
  push: boolean;
  sms: unknown | null;
}

export interface Organization {
  name: string;
  industry: string;
  settings: OrganizationSettings;
}

export interface OrganizationSettings {
  security: Security;
  features: OrganizationSettingsFeatures;
}

export interface OrganizationSettingsFeatures {
  apiAccess: boolean;
  advancedReporting: boolean;
  customBranding: unknown | null;
}

export interface PasswordPolicy {
  minLength: number;
  requireSpecialChars: boolean;
  requireNumbers: boolean;
}

export interface RootStatistics {
  totalUsers: number;
  activeUsers: number;
  growth: number;
}

export interface Security {
  twoFactorRequired: boolean;
  passwordPolicy: PasswordPolicy;
}

export interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  permissions: string[];
  metadata: Metadata;
}
