// Generated by dtolator --json test-output/json-tests/deduplication-test.json --typescript --pretty --root MyApiRoot
// Do not modify manually

export interface Address {
    city: string;
    zip: string;
}

export interface User {
    address: Address;
}

export interface MyApiRoot {
    shippingAddress: Address;
    billingAddress: Address;
    user: User;
} 