// Generated by dtolator --from-openapi test-multiword-tag.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

@Injectable({ providedIn: 'root' })
export class APIKeyManagerApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * List Keys
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<string[]> - ok
   */
  listKeys(headers?: HttpHeaders): Observable<string[]> {
    const url = `${this.baseUrl}/keys`;
    return this.http.get<string[]>(url, { headers });
  }

}

