// Generated by dtolator --from-openapi test-multiword-tag.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type { WidgetDTO } from "./dto";

@Injectable({ providedIn: 'root' })
export class TagWithMultipleWordsApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * List Widgets
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<WidgetDTO[]> - ok
   */
  listWidgets(headers?: HttpHeaders): Observable<WidgetDTO[]> {
    const url = `${this.baseUrl}/widgets`;
    return this.http.get<WidgetDTO[]>(url, { headers });
  }

}

