// Generated by dtolator --from-openapi simple-sample.json --endpoints
// Do not modify manually

// API Endpoint Types

import {
  User,
  UserProfile,
  Address,
  CreateUserRequest,
  ApiResponse
} from './types';

export type ApiEndpoints = {
  "GET /users": {
    response: unknown[];
  };
  "POST /users": {
    request: CreateUserRequest;
    response: ApiResponse;
  };
  "GET /users/{userId}": {
    params: {
      userId: string;
    };
    response: User;
  };
  "PUT /users/{userId}": {
    params: {
      userId: string;
    };
    request: CreateUserRequest;
    response: ApiResponse;
  };
  "DELETE /users/{userId}": {
    params: {
      userId: string;
    };
    response: ApiResponse;
  };
  "POST /users/{userId}/activate": {
    params: {
      userId: string;
    };
    response: ApiResponse;
  };
  "POST /users/{userId}/deactivate": {
    params: {
      userId: string;
    };
    response: ApiResponse;
  };
};

// Helper types for API client usage
export type ExtractEndpointParams<T extends keyof ApiEndpoints> = 
  ApiEndpoints[T] extends { params: infer P } ? P : never;

export type ExtractEndpointQuery<T extends keyof ApiEndpoints> = 
  ApiEndpoints[T] extends { query: infer Q } ? Q : never;

export type ExtractEndpointRequest<T extends keyof ApiEndpoints> = 
  ApiEndpoints[T] extends { request: infer R } ? R : never;

export type ExtractEndpointResponse<T extends keyof ApiEndpoints> = 
  ApiEndpoints[T] extends { response: infer R } ? R : never;

// Utility type to get all GET endpoints
export type GetEndpoints = {
  [K in keyof ApiEndpoints as K extends `GET ${string}` ? K : never]: ApiEndpoints[K]
};

// Utility type to get all POST endpoints  
export type PostEndpoints = {
  [K in keyof ApiEndpoints as K extends `POST ${string}` ? K : never]: ApiEndpoints[K]
};
