// Generated by dtolator --from-json test-data-simple.json --zod
// Do not modify manually

import {
  ProfileSchema,
  ProfileSocialLinksSchema,
  RootAddressSchema,
  RootSchema,
} from "./schema";
import type { Profile, ProfileSocialLinks, Root, RootAddress } from "./schema";

export {
  ProfileSchema,
  ProfileSocialLinksSchema,
  RootAddressSchema,
  RootSchema,
} from "./schema";
export type { Profile, ProfileSocialLinks, Root, RootAddress } from "./schema";
