// Generated by dtolator --json test-output/simple-example.json --zod
// Do not modify manually

import {
  RootSchema,
} from "./schema";
import { z } from "zod";

export type Root = z.infer<typeof RootSchema>;

export { RootSchema };

