// Generated by dtolator --from-json test-data-simple.json --zod
// Do not modify manually

import {
  ProfileSchema,
  ProfileSocialLinksSchema,
  RootAddressSchema,
  RootSchema,
} from "./schema";
import type { Profile, ProfileSocialLinks, Root, RootAddress } from "./schema";

export type { RootAddress };
export type { ProfileSocialLinks };
export type { Profile };
export type { Root };

export { RootAddressSchema };
export { ProfileSocialLinksSchema };
export { ProfileSchema };
export { RootSchema };
