// Generated by dtolator --from-json test-data-simple.json --zod
// Do not modify manually

import { z } from "zod";
export const ProfileSocialLinksSchema = z.object({
  github: z.string(),
  twitter: z.string(),
});

export type ProfileSocialLinks = z.infer<typeof ProfileSocialLinksSchema>;

export const RootAddressSchema = z.object({
  city: z.string(),
  street: z.string(),
  zipCode: z.string(),
});

export type RootAddress = z.infer<typeof RootAddressSchema>;

export const ProfileSchema = z.object({
  avatar: z.unknown().nullable(),
  bio: z.string(),
  socialLinks: ProfileSocialLinksSchema,
});

export type Profile = z.infer<typeof ProfileSchema>;

export const RootSchema = z.object({
  address: RootAddressSchema,
  age: z.number().int(),
  email: z.string(),
  id: z.number().int(),
  isActive: z.boolean(),
  name: z.string(),
  profile: ProfileSchema,
  tags: z.array(z.string()),
});

export type Root = z.infer<typeof RootSchema>;
