// Generated by dtolator --from-json test-data-simple.json --zod
// Do not modify manually

import { z } from "zod";
export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zipCode: z.string(),
});

export type Address = z.infer<typeof AddressSchema>;

export const SocialLinksSchema = z.object({
  github: z.string(),
  twitter: z.string(),
});

export type SocialLinks = z.infer<typeof SocialLinksSchema>;

export const ProfileSchema = z.object({
  bio: z.string(),
  avatar: z.unknown().nullable(),
  socialLinks: SocialLinksSchema,
});

export type Profile = z.infer<typeof ProfileSchema>;

export const RootSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  email: z.string(),
  isActive: z.boolean(),
  age: z.number().int(),
  address: AddressSchema,
  tags: z.array(z.string()),
  profile: ProfileSchema,
});

export type Root = z.infer<typeof RootSchema>;
