// Generated by dtolator --from-json-schema test-zod-all-features.json --zod
// Do not modify manually

import type { Root } from "./schema";
import { RootSchema } from "./schema";

export type { Root };

export { RootSchema };
