// Generated by dtolator --from-json-schema test-zod-all-features.json --zod
// Do not modify manually

import { RootSchema } from "./schema";
import type { Root } from "./schema";

export { RootSchema } from "./schema";
export type { Root } from "./schema";
