// Generated by dtolator --from-json-schema test-zod-all-features.json --zod
// Do not modify manually

import { z } from "zod";

export const RootSchema = z.object({
  basicString: z.string(),
  stringWithConstraints: z.string().min(3).max(50).regex(/^[a-zA-Z]+$/),
  uuid: z.uuid(),
  email: z.email(),
  uri: z.url(),
  date: z.iso.date(),
  dateTime: z.iso.datetime(),
  basicNumber: z.number(),
  numberWithConstraints: z.number().min(0).max(100),
  integer: z.number().int(),
  integerWithRange: z.number().min(1).max(10).int(),
  booleanField: z.boolean(),
  stringArray: z.array(z.string()),
  numberArray: z.array(z.number()),
  objectArray: z.array(z.object({
  id: z.number().int(),
  name: z.string().optional()
})),
  enumField: z.enum(["active", "inactive", "pending"]),
  unionField: z.union([z.string(), z.number()]),
  nestedObject: z.object({
  level1: z.object({
  level2: z.object({
  value: z.string()
})
})
}),
  nullableString: z.string().nullable(),
  optionalField: z.string().optional(),
  complexArray: z.array(z.object({
  tags: z.array(z.string()).optional(),
  score: z.number().min(0).max(1).optional()
})),
  intersectionField: z.intersection([z.object({
  id: z.uuid()
}), z.object({
  email: z.email()
})])
});

export type Root = z.infer<typeof RootSchema>;
