# Generated by dtolator --from-openapi test-nullable-oneof.json --pydantic
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

PaginationCursor = str

class Address(BaseModel):
    street: str
    city: str

class PaginatedResponse(BaseModel):
    cursor: PaginationCursor | None = None
    data: list[str]

NullableMultiType = PaginationCursor | Address | None

AnyOfNullable = Address | None

NonNullableOneOf = PaginationCursor | Address

