# Generated by dtolator --from-openapi test-nullable-oneof.json --pydantic
# Do not modify manually

from pydantic import BaseModel

class Address(BaseModel):
    street: str
    city: str

PaginationCursor = str

AnyOfNullable = Address | None

NonNullableOneOf = PaginationCursor | Address

NullableMultiType = PaginationCursor | Address | None

class PaginatedResponse(BaseModel):
    cursor: PaginationCursor | None = None
    data: list[str]

