// Generated by dtolator --from-openapi test-enum-styles.json --typescript --ts-enum-style enum
// Do not modify manually

/** Lifecycle status of an item */
export enum ItemStatus {
  Draft = "draft",
  Active = "active",
  Archived = "archived",
}

export type NullableColor =
  | "red"
  | "green";

export enum Priority {
  ValueNeg1 = -1,
  Value0 = 0,
  Value1 = 1,
  Value2 = 2,
}

export enum TrickyNames {
  InProgress = "in-progress",
  InProgress_2 = "IN_PROGRESS",
  InProgress_3 = "inProgress",
  _2fa = "2fa",
  Empty = "",
  WithQuotes = "with \"quotes\"",
}

export interface Item {
  id: string;
  status: ItemStatus;
  priority?: Priority;
  color?: NullableColor;
  inlineKind?: "a" | "b";
}
