# Generated by dtolator --from-json test-data-simple.json --pydantic
# Do not modify manually

from typing import Any

from pydantic import BaseModel, Field

class ProfileSocialLinks(BaseModel):
    github: str
    twitter: str

class RootAddress(BaseModel):
    class Config:
        allow_population_by_field_name = True

    city: str
    street: str
    zip_code: str = Field(alias="zipCode")

class Profile(BaseModel):
    class Config:
        allow_population_by_field_name = True

    avatar: Any | None
    bio: str
    social_links: ProfileSocialLinks = Field(alias="socialLinks")

class Root(BaseModel):
    class Config:
        allow_population_by_field_name = True

    address: RootAddress
    age: int
    email: str
    id: int
    is_active: bool = Field(alias="isActive")
    name: str
    profile: Profile
    tags: list[str]

