# Generated by dtolator --from-json test-data-simple.json --pydantic
# Do not modify manually

from typing import Any

from pydantic import BaseModel, Field

class Address(BaseModel):
    class Config:
        allow_population_by_field_name = True

    street: str
    city: str
    zip_code: str = Field(alias="zipCode")

class SocialLinks(BaseModel):
    github: str
    twitter: str

class Profile(BaseModel):
    class Config:
        allow_population_by_field_name = True

    bio: str
    avatar: Any | None
    social_links: SocialLinks = Field(alias="socialLinks")

class Root(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: int
    name: str
    email: str
    is_active: bool = Field(alias="isActive")
    age: int
    address: Address
    tags: list[str]
    profile: Profile

