# Generated by dtolator --json test-output/json-tests/simple-example.json --pydantic --pretty --root MyApiRoot
# Do not modify manually

from pydantic import BaseModel, Field
from typing import Optional, Union, List, Dict, Any
from enum import Enum
from datetime import datetime

class Profile(BaseModel):
    age: int
    city: str

class Projects(BaseModel):
    name: str
    status: str
    year: int

class MyApiRoot(BaseModel):
    email: str
    id: int
    isActive: bool
    name: str
    profile: Profile
    projects: List[Projects]
    score: float
    tags: List[str] 