# Generated by dtolator --from-openapi test-allof-composition.json --python-dict
# Do not modify manually

from typing import TypedDict, Literal, Any
from enum import Enum, IntEnum
from datetime import datetime

class BaseEntityRequired(TypedDict):
    id: str


class BaseEntity(BaseEntityRequired, total=False):
    createdAt: str

class UserRequired(BaseEntity):
    displayName: str


class User(UserRequired, total=False):
    emailAddress: str

