# Generated by dtolator --from-openapi test-allof-composition.json --pydantic
# Do not modify manually

from datetime import datetime

from pydantic import BaseModel, Field

class BaseEntity(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: str
    created_at: datetime | None = Field(None, alias="createdAt")

class User(BaseModel):
    # This model combines multiple schemas (allOf)
    class Config:
        allow_population_by_field_name = True

    # Inherits from BaseEntity
    display_name: str = Field(alias="displayName")
    email_address: str | None = Field(None, alias="emailAddress")


