# Generated by dtolator --from-json test-data-complex.json --pydantic --pydantic-version 2
# Do not modify manually

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

class Features(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    api_access: bool = Field(alias="apiAccess")
    advanced_reporting: bool = Field(alias="advancedReporting")
    custom_branding: Any | None = Field(alias="customBranding")

class Notifications(BaseModel):
    email: bool
    push: bool
    sms: Any | None

class PasswordPolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    min_length: int = Field(alias="minLength")
    require_special_chars: bool = Field(alias="requireSpecialChars")
    require_numbers: bool = Field(alias="requireNumbers")

class Statistics(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total_users: int = Field(alias="totalUsers")
    active_users: int = Field(alias="activeUsers")
    growth: float

class Preferences(BaseModel):
    theme: str
    language: str
    notifications: Notifications

class Security(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    two_factor_required: bool = Field(alias="twoFactorRequired")
    password_policy: PasswordPolicy = Field(alias="passwordPolicy")

class Metadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    created_at: str = Field(alias="createdAt")
    last_login: str = Field(alias="lastLogin")
    preferences: Preferences

class Settings(BaseModel):
    security: Security
    features: Features

class User(BaseModel):
    id: int
    name: str
    email: str
    role: str
    permissions: list[str]
    metadata: Metadata

class Organization(BaseModel):
    name: str
    industry: str
    settings: Settings

class Root(BaseModel):
    users: list[User]
    organization: Organization
    statistics: Statistics

