# Generated by dtolator --from-json test-data-complex.json --pydantic-v2
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

class OrganizationSettingsFeatures(BaseModel):
    advancedReporting: bool
    apiAccess: bool
    customBranding: Any | None

class PasswordPolicy(BaseModel):
    minLength: int
    requireNumbers: bool
    requireSpecialChars: bool

class Security(BaseModel):
    passwordPolicy: PasswordPolicy
    twoFactorRequired: bool

class OrganizationSettings(BaseModel):
    features: OrganizationSettingsFeatures
    security: Security

class Organization(BaseModel):
    industry: str
    name: str
    settings: OrganizationSettings

class RootStatistics(BaseModel):
    activeUsers: int
    growth: float
    totalUsers: int

class MetadataPreferencesNotifications(BaseModel):
    email: bool
    push: bool
    sms: Any | None

class MetadataPreferences(BaseModel):
    language: str
    notifications: MetadataPreferencesNotifications
    theme: str

class Metadata(BaseModel):
    createdAt: str
    lastLogin: str
    preferences: MetadataPreferences

class User(BaseModel):
    email: str
    id: int
    metadata: Metadata
    name: str
    permissions: list[str]
    role: str

class Root(BaseModel):
    organization: Organization
    statistics: RootStatistics
    users: list[User]


