// Generated by dtolator --from-openapi simple-sample.json --zod --angular --base-url-mode argument
// Do not modify manually

import type { Address, UserProfile } from "./schema";

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}
