// Generated by dtolator --from-openapi simple-sample.json --zod --angular
// Do not modify manually

import {
  AddressSchema,
  ApiResponseSchema,
  UserProfileSchema,
  UserSchema,
} from "./schema";
import type { Address, ApiResponse, User, UserProfile } from "./schema";

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}

export {
  AddressSchema,
  ApiResponseSchema,
  UserProfileSchema,
  UserSchema,
} from "./schema";
export type { Address, ApiResponse, User, UserProfile } from "./schema";
