// Generated by dtolator --from-openapi simple-sample.json --zod --angular --base-url-mode argument
// Do not modify manually

import { z } from "zod";
/**
 * A physical mailing address.
 *
 * All addresses must include at least `street`, `city`, and `country`.
 * The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
 */
export const AddressSchema = z.object({
  street: z.string().min(1).max(100),
  city: z.string().min(1).max(50),
  state: z.string().max(50).nullable().optional(),
  /** ISO 3166-1 alpha-2 country code */
  country: z.string().regex(/^[A-Z]{2}$/),
  postalCode: z.string().min(3).max(10).nullable().optional(),
});

export type Address = z.infer<typeof AddressSchema>;

export const UserProfileSchema = z.object({
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  phoneNumber: z.string().regex(/^\\+?[1-9]\\d{1,14}$/).nullable().optional(),
  avatar: z.url().nullable().optional(),
  bio: z.string().max(500).nullable().optional(),
});

export type UserProfile = z.infer<typeof UserProfileSchema>;

export const CreateUserRequestSchema = z.object({
  email: z.email(),
  name: z.string().min(1).max(100),
  age: z.number().min(0).max(150).int().nullable().optional(),
  profile: UserProfileSchema,
  address: AddressSchema.optional(),
});

export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

/**
 * Represents a user in the system.
 *
 * A user can be in one of the following states:
 * - **active**: The user can log in and use the system.
 * - **inactive**: The user account is disabled.
 * - **pending**: The user has registered but not yet confirmed their email.
 *
 * See also: `UserProfile` for extended profile information.
 */
export const UserSchema = z.object({
  id: z.number().int(),
  /**
   * The user's primary email address.
   * Must be unique across the system.
   * Used for login and notifications.
   */
  email: z.email(),
  name: z.string().min(1).max(100),
  age: z.number().min(0).max(150).int().optional(),
  isActive: z.boolean().optional(),
  tags: z.array(z.string()).optional(),
  status: z.enum(["active", "inactive", "pending"]).optional(),
  profile: UserProfileSchema.optional(),
  address: AddressSchema.optional(),
});

export type User = z.infer<typeof UserSchema>;

export const ApiResponseSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
  data: UserSchema.optional(),
});

export type ApiResponse = z.infer<typeof ApiResponseSchema>;
