// Generated by dtolator --from-openapi test-ref-description.json --typescript
// Do not modify manually

export interface Address {
  street: string;
  city: string;
}

export interface ContactInfo {
  email: string;
  phone?: string;
}

export interface Person {
  /** Full name of the person */
  name: string;
  /** Primary residential address */
  homeAddress: Address;
  workAddress?: Address;
  /** Contact information if available */
  contact?: unknown | null | ContactInfo;
  /** Address used for billing */
  billingAddress?: unknown | null | Address;
}
