# Generated by dtolator --from-openapi simple-sample.json --pydantic --pydantic-version 2
# Do not modify manually

from typing import Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field, HttpUrl

class Address(BaseModel):
    """
    A physical mailing address.

    All addresses must include at least `street`, `city`, and `country`.
    The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
    """
    model_config = ConfigDict(populate_by_name=True)

    street: str = Field(min_length=1, max_length=100)
    city: str = Field(min_length=1, max_length=50)
    state: str | None = Field(None, max_length=50)
    country: str = Field(pattern=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code")
    postal_code: str | None = Field(None, alias="postalCode", min_length=3, max_length=10)

class UserProfile(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    first_name: str = Field(alias="firstName", min_length=1, max_length=50)
    last_name: str = Field(alias="lastName", min_length=1, max_length=50)
    phone_number: str | None = Field(None, alias="phoneNumber", pattern=r"^\+?[1-9]\d{1,14}$")
    avatar: HttpUrl | None = None
    bio: str | None = Field(None, max_length=500)

class CreateUserRequest(BaseModel):
    email: EmailStr
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    profile: UserProfile
    address: Address | None = None

class User(BaseModel):
    """
    Represents a user in the system.

    A user can be in one of the following states:
    - **active**: The user can log in and use the system.
    - **inactive**: The user account is disabled.
    - **pending**: The user has registered but not yet confirmed their email.

    See also: `UserProfile` for extended profile information.
    """
    model_config = ConfigDict(populate_by_name=True)

    id: int
    email: EmailStr = Field(description="The user's primary email address.\nMust be unique across the system.\nUsed for login and notifications.")
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    is_active: bool | None = Field(None, alias="isActive")
    tags: list[str] | None = None
    status: Literal["active", "inactive", "pending"] | None = None
    profile: UserProfile | None = None
    address: Address | None = None

class ApiResponse(BaseModel):
    success: bool
    message: str | None = None
    data: User | None = None

