# Generated by dtolator --from-openapi simple-sample.json --pydantic --pydantic-version 2
# Do not modify manually

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Any, Literal
from enum import Enum
from datetime import date, datetime
from uuid import UUID

class User(BaseModel):
    """
    Represents a user in the system.

    A user can be in one of the following states:
    - **active**: The user can log in and use the system.
    - **inactive**: The user account is disabled.
    - **pending**: The user has registered but not yet confirmed their email.

    See also: `UserProfile` for extended profile information.
    """
    id: int
    email: EmailStr = Field(description="The user's primary email address.\nMust be unique across the system.\nUsed for login and notifications.")
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    isActive: bool | None = None
    tags: list[str] | None = None
    status: Literal["active", "inactive", "pending"] | None = None
    profile: UserProfile | None = None
    address: Address | None = None

class UserProfile(BaseModel):
    firstName: str = Field(min_length=1, max_length=50)
    lastName: str = Field(min_length=1, max_length=50)
    phoneNumber: str | None = Field(None, pattern=r"^\+?[1-9]\d{1,14}$")
    avatar: HttpUrl | None = None
    bio: str | None = Field(None, max_length=500)

class Address(BaseModel):
    """
    A physical mailing address.

    All addresses must include at least `street`, `city`, and `country`.
    The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
    """
    street: str = Field(min_length=1, max_length=100)
    city: str = Field(min_length=1, max_length=50)
    state: str | None = Field(None, max_length=50)
    country: str = Field(pattern=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code")
    postalCode: str | None = Field(None, min_length=3, max_length=10)

class CreateUserRequest(BaseModel):
    email: EmailStr
    name: str = Field(min_length=1, max_length=100)
    age: int | None = Field(None, ge=0, le=150)
    profile: UserProfile
    address: Address | None = None

class ApiResponse(BaseModel):
    success: bool
    message: str | None = None
    data: User | None = None

