# Generated by dtolator --from-json test-pydantic-advanced.json --pydantic
# Do not modify manually

from pydantic import BaseModel, Field
from typing import Optional, Union, List, Dict, Any
from enum import Enum
from datetime import datetime


class MetadataPreferences(BaseModel):
    language: str
    notifications: bool
    theme: str


class Metadata(BaseModel):
    accountType: str
    lastLogin: str
    loginCount: int
    preferences: MetadataPreferences


class Profile(BaseModel):
    avatar: str
    displayName: str
    firstName: str
    lastName: str
    middleName: Optional[Any]
    rating: float
    reviewCount: int
    verified: bool


class User(BaseModel):
    age: int
    bio: str
    birthDate: str
    email: str
    metadata: Metadata
    password: str
    phonePattern: str
    profile: Profile
    registeredAt: str
    roles: List[str]
    score: float
    status: str
    tags: List[str]
    userId: str
    username: str
    website: str


class Root(BaseModel):
    user: User
