// Generated by dtolator --from-openapi simple-sample.json --dotnet
// Do not modify manually

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

/// <summary>
/// Represents a user in the system.
/// 
/// A user can be in one of the following states:
/// - **active**: The user can log in and use the system.
/// - **inactive**: The user account is disabled.
/// - **pending**: The user has registered but not yet confirmed their email.
/// 
/// See also: `UserProfile` for extended profile information.
/// </summary>
public record User
{
    [JsonPropertyName("id")]
    public required long Id { get; set; }
    [JsonPropertyName("email")]
    public required string Email { get; set; }
    [JsonPropertyName("name")]
    public required string Name { get; set; }
    [JsonPropertyName("age")]
    public int? Age { get; set; }
    [JsonPropertyName("isActive")]
    public bool? IsActive { get; set; }
    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; }
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    [JsonPropertyName("profile")]
    public UserProfile? Profile { get; set; }
    [JsonPropertyName("address")]
    public Address? Address { get; set; }
}

public record UserProfile
{
    [JsonPropertyName("firstName")]
    public required string FirstName { get; set; }
    [JsonPropertyName("lastName")]
    public required string LastName { get; set; }
    [JsonPropertyName("phoneNumber")]
    public string? PhoneNumber { get; set; }
    [JsonPropertyName("avatar")]
    public string? Avatar { get; set; }
    [JsonPropertyName("bio")]
    public string? Bio { get; set; }
}

/// <summary>
/// A physical mailing address.
/// 
/// All addresses must include at least `street`, `city`, and `country`.
/// The `country` field uses ISO 3166-1 alpha-2 codes (e.g. `US`, `FI`, `DE`).
/// </summary>
public record Address
{
    [JsonPropertyName("street")]
    public required string Street { get; set; }
    [JsonPropertyName("city")]
    public required string City { get; set; }
    [JsonPropertyName("state")]
    public string? State { get; set; }
    [JsonPropertyName("country")]
    public required string Country { get; set; }
    [JsonPropertyName("postalCode")]
    public string? PostalCode { get; set; }
}

public record CreateUserRequest
{
    [JsonPropertyName("email")]
    public required string Email { get; set; }
    [JsonPropertyName("name")]
    public required string Name { get; set; }
    [JsonPropertyName("age")]
    public int? Age { get; set; }
    [JsonPropertyName("profile")]
    public required UserProfile Profile { get; set; }
    [JsonPropertyName("address")]
    public Address? Address { get; set; }
}

public record ApiResponse
{
    [JsonPropertyName("success")]
    public required bool Success { get; set; }
    [JsonPropertyName("message")]
    public string? Message { get; set; }
    [JsonPropertyName("data")]
    public User? Data { get; set; }
}

