# Generated by dtolator --from-openapi full-sample.json --pydantic
# Do not modify manually

from datetime import date, datetime
from enum import Enum, IntEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, HttpUrl

class Address(BaseModel):
    """
    Physical mailing or shipping address.
    Used for both billing and delivery purposes.
    """
    class Config:
        allow_population_by_field_name = True

    street: str = Field(min_length=1, max_length=100)
    street2: str | None = Field(None, max_length=100)
    city: str = Field(min_length=1, max_length=50)
    state: str | None = Field(None, max_length=50)
    country: str = Field(regex=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code")
    postal_code: str = Field(alias="postalCode", min_length=3, max_length=10)

class Category(BaseModel):
    """Product category with optional hierarchy"""
    class Config:
        allow_population_by_field_name = True

    id: UUID
    name: str = Field(min_length=1, max_length=100)
    slug: str = Field(regex=r"^[a-z0-9-]+$")
    description: str | None = Field(None, max_length=500)
    parent_id: UUID | None = Field(None, alias="parentId")
    is_active: bool | None = Field(None, alias="isActive")

class CreateCategoryRequest(BaseModel):
    """Request body for creating a new category"""
    class Config:
        allow_population_by_field_name = True

    name: str = Field(min_length=1, max_length=100)
    slug: str = Field(regex=r"^[a-z0-9-]+$")
    description: str | None = Field(None, max_length=500)
    parent_id: UUID | None = Field(None, alias="parentId")

class ErrorResponse(BaseModel):
    """Standard error response envelope"""
    error: dict[str, Any]

class ImageUrl(BaseModel):
    """Image with URL and optional metadata"""
    url: HttpUrl = Field(description="Image URL")
    alt: str | None = Field(None, description="Alternative text for the image")
    width: int | None = Field(None, ge=1)
    height: int | None = Field(None, ge=1)

class Inventory(BaseModel):
    """Stock level and availability for a product"""
    class Config:
        allow_population_by_field_name = True

    quantity: int = Field(ge=0)
    status: Literal["in_stock", "low_stock", "out_of_stock", "discontinued"]
    low_stock_threshold: int | None = Field(None, alias="lowStockThreshold", ge=0)

class NotificationSettings(BaseModel):
    """Per-channel notification opt-in settings"""
    email: bool | None = None
    push: bool | None = None
    sms: bool | None = None
    marketing: bool | None = None

class OrderStatus(str, Enum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    PROCESSING = "processing"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"
    REFUNDED = "refunded"


class PaginationInfo(BaseModel):
    """Pagination metadata for list responses"""
    class Config:
        allow_population_by_field_name = True

    page: int = Field(ge=1)
    limit: int = Field(ge=1)
    total: int = Field(ge=0)
    total_pages: int = Field(alias="totalPages", ge=0)
    has_next: bool | None = Field(None, alias="hasNext")
    has_prev: bool | None = Field(None, alias="hasPrev")

class PaymentMethod(BaseModel):
    """Payment instrument used for an order"""
    type: Literal["credit_card", "debit_card", "paypal", "bank_transfer", "crypto"]
    last4: str | None = Field(None, regex=r"^[0-9]{4}$", description="Last 4 digits of card (for card payments)")
    brand: Literal["visa", "mastercard", "amex", "discover"] | None = Field(None, description="Card brand (for card payments)")

class Price(BaseModel):
    """Monetary amount with currency"""
    class Config:
        allow_population_by_field_name = True

    amount: float = Field(ge=0)
    currency: Literal["USD", "EUR", "GBP", "JPY"]
    original_amount: float | None = Field(None, alias="originalAmount", ge=0, description="Original price before discount")

class Priority(IntEnum):
    VALUE_1 = 1
    VALUE_2 = 2
    VALUE_3 = 3


class ProductAnalytics(BaseModel):
    """Catalog statistics and stock health metrics"""
    class Config:
        allow_population_by_field_name = True

    total_products: int = Field(alias="totalProducts", ge=0)
    active_products: int = Field(alias="activeProducts", ge=0)
    category_breakdown: dict[str, int] | None = Field(None, alias="categoryBreakdown")
    low_stock_products: list[dict[str, Any]] | None = Field(None, alias="lowStockProducts")

class ProductCategory(str, Enum):
    ELECTRONICS = "electronics"
    CLOTHING = "clothing"
    HOME = "home"
    BOOKS = "books"
    SPORTS = "sports"
    BEAUTY = "beauty"
    AUTOMOTIVE = "automotive"


class SalesAnalytics(BaseModel):
    """Aggregated sales metrics for a given period"""
    class Config:
        allow_population_by_field_name = True

    total_revenue: float = Field(alias="totalRevenue", ge=0)
    total_orders: int = Field(alias="totalOrders", ge=0)
    average_order_value: float = Field(alias="averageOrderValue", ge=0)
    top_products: list[dict[str, Any]] | None = Field(None, alias="topProducts")
    period: dict[str, Any] | None = None

class UpdateInventoryRequest(BaseModel):
    """Request body for updating product inventory"""
    class Config:
        allow_population_by_field_name = True

    quantity: int = Field(ge=0)
    low_stock_threshold: int | None = Field(None, alias="lowStockThreshold", ge=0)

class UserRole(str, Enum):
    CUSTOMER = "customer"
    ADMIN = "admin"
    MODERATOR = "moderator"
    VENDOR = "vendor"


class UserProfile(BaseModel):
    """Personal profile information for a user"""
    class Config:
        allow_population_by_field_name = True

    first_name: str = Field(alias="firstName", min_length=1, max_length=50)
    last_name: str = Field(alias="lastName", min_length=1, max_length=50)
    date_of_birth: date | None = Field(None, alias="dateOfBirth")
    phone_number: str | None = Field(None, alias="phoneNumber", regex=r"^\+?[1-9]\d{1,14}$")
    avatar: ImageUrl | None = None
    address: Address | None = None

class InventoryResponse(BaseModel):
    """Inventory levels for a list of products"""
    data: list[dict[str, Any]]

class UserPreferences(BaseModel):
    """User-configurable application preferences"""
    language: Literal["en", "es", "fr", "de", "it"] | None = None
    currency: Literal["USD", "EUR", "GBP", "JPY"] | None = None
    notifications: NotificationSettings | None = None
    theme: Literal["light", "dark", "auto"] | None = None

class UpdateOrderStatusRequest(BaseModel):
    """Request body for updating an order's status"""
    class Config:
        allow_population_by_field_name = True

    status: OrderStatus
    tracking_number: str | None = Field(None, alias="trackingNumber")

class CreateOrderRequest(BaseModel):
    """Request body for placing a new order"""
    class Config:
        allow_population_by_field_name = True

    items: list[dict[str, Any]]
    shipping_address: Address = Field(alias="shippingAddress")
    billing_address: Address | None = Field(None, alias="billingAddress")
    payment_method: PaymentMethod | None = Field(None, alias="paymentMethod")

class Product(BaseModel):
    """A product listed in the catalog"""
    class Config:
        allow_population_by_field_name = True

    id: UUID
    name: str = Field(min_length=1, max_length=200)
    description: str | None = Field(None, max_length=2000)
    price: Price
    category: ProductCategory
    tags: list[str] | None = None
    images: list[ImageUrl] | None = None
    inventory: Inventory | None = None
    specifications: dict[str, str | float | bool] | None = None
    is_active: bool | None = Field(None, alias="isActive")
    created_at: datetime | None = Field(None, alias="createdAt")

class UpdateProductRequest(BaseModel):
    """Request body for partially updating a product"""
    class Config:
        allow_population_by_field_name = True

    name: str | None = Field(None, min_length=1, max_length=200)
    description: str | None = Field(None, max_length=2000)
    price: Price | None = None
    category: ProductCategory | None = None
    is_active: bool | None = Field(None, alias="isActive")

class CreateUserRequest(BaseModel):
    """Request body for creating a new user account"""
    email: EmailStr
    password: str = Field(min_length=8, max_length=128, regex=r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]")
    profile: UserProfile
    preferences: UserPreferences | None = None

class User(BaseModel):
    """Registered user account"""
    class Config:
        allow_population_by_field_name = True

    id: UUID = Field(description="Unique user identifier")
    email: EmailStr = Field(description="User's email address")
    profile: UserProfile
    preferences: UserPreferences | None = None
    created_at: datetime | None = Field(None, alias="createdAt")
    updated_at: datetime | None = Field(None, alias="updatedAt")
    is_active: bool | None = Field(None, alias="isActive")
    roles: list[UserRole] | None = None

class OrderItem(BaseModel):
    """A single line item within an order"""
    class Config:
        allow_population_by_field_name = True

    product_id: UUID = Field(alias="productId")
    quantity: int = Field(ge=1)
    price: Price
    product_snapshot: Product | None = Field(None, alias="productSnapshot", description="Snapshot of product at time of order")

class ProductListResponse(BaseModel):
    """Paginated list of products with optional filters"""
    data: list[Product]
    pagination: PaginationInfo
    filters: dict[str, Any] | None = None

class UserListResponse(BaseModel):
    """Paginated list of users"""
    data: list[User]
    pagination: PaginationInfo

class Order(BaseModel):
    """A customer purchase order"""
    class Config:
        allow_population_by_field_name = True

    id: UUID
    user_id: UUID = Field(alias="userId")
    items: list[OrderItem]
    total: Price
    status: OrderStatus
    priority: Priority | None = None
    shipping_address: Address | None = Field(None, alias="shippingAddress")
    billing_address: Address | None = Field(None, alias="billingAddress")
    payment_method: PaymentMethod | None = Field(None, alias="paymentMethod")
    order_date: datetime | None = Field(None, alias="orderDate")
    estimated_delivery: date | None = Field(None, alias="estimatedDelivery")
    tracking_number: str | None = Field(None, alias="trackingNumber")

