// Generated by dtolator --from-openapi simple-sample.json --zod --angular
// Do not modify manually

import {
  User,
  UserSchema,
  UserProfile,
  UserProfileSchema,
  Address,
  AddressSchema,
  ApiResponse,
  ApiResponseSchema,
} from "./schema";
import { z } from "zod";

export interface CreateUserRequest {
  email: string;
  name: string;
  age?: number | null;
  profile: UserProfile;
  address?: Address;
}

export type { User };
export type { UserProfile };
export type { Address };
export type { ApiResponse };

export { UserSchema };
export { UserProfileSchema };
export { AddressSchema };
export { ApiResponseSchema };

