# Generated by dtolator --from-json test-data-complex.json --pydantic
# Do not modify manually

from typing import Any

from pydantic import BaseModel, Field

class MetadataPreferencesNotifications(BaseModel):
    email: bool
    push: bool
    sms: Any | None

class OrganizationSettingsFeatures(BaseModel):
    class Config:
        allow_population_by_field_name = True

    api_access: bool = Field(alias="apiAccess")
    advanced_reporting: bool = Field(alias="advancedReporting")
    custom_branding: Any | None = Field(alias="customBranding")

class PasswordPolicy(BaseModel):
    class Config:
        allow_population_by_field_name = True

    min_length: int = Field(alias="minLength")
    require_special_chars: bool = Field(alias="requireSpecialChars")
    require_numbers: bool = Field(alias="requireNumbers")

class RootStatistics(BaseModel):
    class Config:
        allow_population_by_field_name = True

    total_users: int = Field(alias="totalUsers")
    active_users: int = Field(alias="activeUsers")
    growth: float

class MetadataPreferences(BaseModel):
    theme: str
    language: str
    notifications: MetadataPreferencesNotifications

class Security(BaseModel):
    class Config:
        allow_population_by_field_name = True

    two_factor_required: bool = Field(alias="twoFactorRequired")
    password_policy: PasswordPolicy = Field(alias="passwordPolicy")

class Metadata(BaseModel):
    class Config:
        allow_population_by_field_name = True

    created_at: str = Field(alias="createdAt")
    last_login: str = Field(alias="lastLogin")
    preferences: MetadataPreferences

class OrganizationSettings(BaseModel):
    security: Security
    features: OrganizationSettingsFeatures

class User(BaseModel):
    id: int
    name: str
    email: str
    role: str
    permissions: list[str]
    metadata: Metadata

class Organization(BaseModel):
    name: str
    industry: str
    settings: OrganizationSettings

class Root(BaseModel):
    users: list[User]
    organization: Organization
    statistics: RootStatistics

