# Generated by dtolator --from-json test-data-complex.json --pydantic
# Do not modify manually

from typing import Any

from pydantic import BaseModel, Field

class MetadataPreferencesNotifications(BaseModel):
    email: bool
    push: bool
    sms: Any | None

class OrganizationSettingsFeatures(BaseModel):
    class Config:
        allow_population_by_field_name = True

    advanced_reporting: bool = Field(alias="advancedReporting")
    api_access: bool = Field(alias="apiAccess")
    custom_branding: Any | None = Field(alias="customBranding")

class PasswordPolicy(BaseModel):
    class Config:
        allow_population_by_field_name = True

    min_length: int = Field(alias="minLength")
    require_numbers: bool = Field(alias="requireNumbers")
    require_special_chars: bool = Field(alias="requireSpecialChars")

class RootStatistics(BaseModel):
    class Config:
        allow_population_by_field_name = True

    active_users: int = Field(alias="activeUsers")
    growth: float
    total_users: int = Field(alias="totalUsers")

class MetadataPreferences(BaseModel):
    language: str
    notifications: MetadataPreferencesNotifications
    theme: str

class Security(BaseModel):
    class Config:
        allow_population_by_field_name = True

    password_policy: PasswordPolicy = Field(alias="passwordPolicy")
    two_factor_required: bool = Field(alias="twoFactorRequired")

class Metadata(BaseModel):
    class Config:
        allow_population_by_field_name = True

    created_at: str = Field(alias="createdAt")
    last_login: str = Field(alias="lastLogin")
    preferences: MetadataPreferences

class OrganizationSettings(BaseModel):
    features: OrganizationSettingsFeatures
    security: Security

class User(BaseModel):
    email: str
    id: int
    metadata: Metadata
    name: str
    permissions: list[str]
    role: str

class Organization(BaseModel):
    industry: str
    name: str
    settings: OrganizationSettings

class Root(BaseModel):
    organization: Organization
    statistics: RootStatistics
    users: list[User]

