// Generated by dtolator --from-json-schema schema.json --typescript
// Do not modify manually

export interface Address {
  city: string;
  street: string;
  zipCode: string;
}

export interface SocialLinks {
  github: string;
  twitter: string;
}

export interface Profile {
  avatar: unknown | null;
  bio: string;
  socialLinks: SocialLinks;
}

/** Schema generated from plain JSON input */
export interface Root {
  address: Address;
  age: number;
  email: string;
  id: number;
  isActive: boolean;
  name: string;
  profile: Profile;
  tags: string[];
}
