# Generated by dtolator --from-openapi test-allof-composition.json --pydantic --pydantic-version 2
# Do not modify manually

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

class BaseEntity(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    created_at: datetime | None = Field(None, alias="createdAt")

class User(BaseModel):
    # This model combines multiple schemas (allOf)
    model_config = ConfigDict(populate_by_name=True)

    # Inherits from BaseEntity
    display_name: str = Field(alias="displayName")
    email_address: str | None = Field(None, alias="emailAddress")


