// Generated by dtolator --from-openapi test-multipart.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type { FileInfo } from "./dto";

@Injectable({ providedIn: 'root' })
export class FilesApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Get File Information
   *
   * Retrieve metadata for an uploaded file
   *
   * @param fileId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<FileInfo> - File information retrieved
   */
  getFileInformation(fileId: string, headers?: HttpHeaders): Observable<FileInfo> {
    const url = `${this.baseUrl}/files/${encodeURIComponent(fileId)}`;
    return this.http.get<FileInfo>(url, { headers });
  }

}

