// Generated by dtolator --from-openapi test-multipart.json --angular
// Do not modify manually

import { HttpClient, HttpHeaders } from "@angular/common/http";
import { Injectable, inject } from "@angular/core";
import type { Observable } from "rxjs";

import type {
  MultiUploadResponse,
  ProfileResponse,
  ProfileUploadRequest,
  UpdateProjectFilesDto,
  UploadMultipleDocumentsDto,
  UploadResponse,
  UploadUserAvatarDto,
} from "./dto";

@Injectable({ providedIn: 'root' })
export class UploadApi {
  private http = inject(HttpClient);
  private baseUrl: string;

  constructor() {
    this.baseUrl = (globalThis as any).API_URL || (typeof window !== 'undefined' && (window as any).API_URL);
    if (!this.baseUrl) throw new Error('API_URL is not configured');
  }

  /**
   * Upload User Avatar
   *
   * Upload a single avatar image file
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<UploadResponse> - Avatar uploaded successfully
   */
  uploadUserAvatar(data: UploadUserAvatarDto, headers?: HttpHeaders): Observable<UploadResponse> {
    const url = `${this.baseUrl}/upload/avatar`;
    const formData = new FormData();
    formData.append('file', data.file);
    formData.append('userId', String(data.userId));
    if (data.description) {
      formData.append('description', data.description);
    }
    return this.http.post<UploadResponse>(url, formData, { headers });
  }

  /**
   * Upload Multiple Documents
   *
   * Upload multiple document files with metadata
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<MultiUploadResponse> - Documents uploaded successfully
   */
  uploadMultipleDocuments(data: UploadMultipleDocumentsDto, headers?: HttpHeaders): Observable<MultiUploadResponse> {
    const url = `${this.baseUrl}/upload/documents`;
    const formData = new FormData();
    data.files.forEach(item => formData.append('files', item));
    formData.append('category', data.category);
    if (data.tags) {
      data.tags.forEach(item => formData.append('tags', item));
    }
    if (data.isPublic) {
      formData.append('isPublic', String(data.isPublic));
    }
    return this.http.post<MultiUploadResponse>(url, formData, { headers });
  }

  /**
   * Upload Profile with Photo
   *
   * Create a user profile with photo and detailed information
   *
   * @param headers - Optional HTTP headers
   * @returns Observable<ProfileResponse> - Profile created successfully
   */
  uploadProfileWithPhoto(data: ProfileUploadRequest, headers?: HttpHeaders): Observable<ProfileResponse> {
    const url = `${this.baseUrl}/upload/profile`;
    const formData = new FormData();
    formData.append('email', data.email);
    formData.append('firstName', data.firstName);
    formData.append('lastName', data.lastName);
    formData.append('photo', data.photo);
    if (data.dateOfBirth) {
      formData.append('dateOfBirth', data.dateOfBirth);
    }
    if (data.phoneNumber) {
      formData.append('phoneNumber', data.phoneNumber);
    }
    if (data.bio) {
      formData.append('bio', data.bio);
    }
    if (data.resume) {
      formData.append('resume', data.resume);
    }
    return this.http.post<ProfileResponse>(url, formData, { headers });
  }

  /**
   * Update Project Files
   *
   * Update project with new files and metadata
   *
   * @param projectId - Path parameter of type string
   * @param headers - Optional HTTP headers
   * @returns Observable<UploadResponse> - Project updated successfully
   */
  updateProjectFiles(projectId: string, data: UpdateProjectFilesDto, headers?: HttpHeaders): Observable<UploadResponse> {
    const url = `${this.baseUrl}/upload/mixed/${encodeURIComponent(projectId)}`;
    const formData = new FormData();
    formData.append('name', data.name);
    if (data.thumbnail) {
      formData.append('thumbnail', data.thumbnail);
    }
    if (data.attachments) {
      data.attachments.forEach(item => formData.append('attachments', item));
    }
    if (data.metadata) {
      formData.append('metadata', JSON.stringify(data.metadata));
    }
    return this.http.put<UploadResponse>(url, formData, { headers });
  }

}

