// Generated by dtolator --from-json test-deep-nesting.json --typescript
// Do not modify manually

export interface Root {
  level1: Level1;
}

export interface Level1 {
  id: string;
  name: string;
  level2: Level2;
}

export interface Level2 {
  id: string;
  name: string;
  level3: Level3;
}

export interface Level3 {
  id: string;
  name: string;
  level4: Level4;
}

export interface Level4 {
  id: string;
  name: string;
  level5: Level5;
}

export interface Level5 {
  id: string;
  name: string;
  level6: Level6;
}

export interface Level6 {
  id: string;
  name: string;
  data: string;
  array: number[];
}
