// Generated by dtolator --from-openapi test-nullable-oneof.json --zod
// Do not modify manually

import {
  AddressSchema,
  AnyOfNullableSchema,
  NonNullableOneOfSchema,
  NullableMultiTypeSchema,
  PaginatedResponseSchema,
  PaginationCursorSchema,
} from "./schema";
import type {
  Address,
  AnyOfNullable,
  NonNullableOneOf,
  NullableMultiType,
  PaginatedResponse,
  PaginationCursor,
} from "./schema";

export {
  AddressSchema,
  AnyOfNullableSchema,
  NonNullableOneOfSchema,
  NullableMultiTypeSchema,
  PaginatedResponseSchema,
  PaginationCursorSchema,
} from "./schema";
export type {
  Address,
  AnyOfNullable,
  NonNullableOneOf,
  NullableMultiType,
  PaginatedResponse,
  PaginationCursor,
} from "./schema";
