// Generated by dtolator --from-openapi test-nullable-oneof.json --zod
// Do not modify manually

import { z } from "zod";
export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
});

export type Address = z.infer<typeof AddressSchema>;

/** An opaque cursor for pagination */
export const PaginationCursorSchema = z.string();

export type PaginationCursor = z.infer<typeof PaginationCursorSchema>;

/** An anyOf with null */
export const AnyOfNullableSchema = AddressSchema.nullable();

export type AnyOfNullable = z.infer<typeof AnyOfNullableSchema>;

/** A oneOf without null should remain a plain union */
export const NonNullableOneOfSchema = z.union([
  PaginationCursorSchema,
  AddressSchema
]);

export type NonNullableOneOf = z.infer<typeof NonNullableOneOfSchema>;

/** A oneOf with null and multiple non-null types */
export const NullableMultiTypeSchema = z.union([
  PaginationCursorSchema,
  AddressSchema
]).nullable();

export type NullableMultiType = z.infer<typeof NullableMultiTypeSchema>;

export const PaginatedResponseSchema = z.object({
  cursor: PaginationCursorSchema.nullable().optional(),
  data: z.array(z.string()),
});

export type PaginatedResponse = z.infer<typeof PaginatedResponseSchema>;
