// Generated by dtolator --from-openapi test-multipart.json --zod --angular
// Do not modify manually

import {
  FileInfoSchema,
  MultiUploadResponseSchema,
  ProfileResponseSchema,
  UploadResponseSchema,
} from "./schema";
import type {
  FileInfo,
  MultiUploadResponse,
  ProfileResponse,
  UploadResponse,
} from "./schema";

export {
  FileInfoSchema,
  MultiUploadResponseSchema,
  ProfileResponseSchema,
  UploadResponseSchema,
} from "./schema";
export type {
  FileInfo,
  MultiUploadResponse,
  ProfileResponse,
  UploadResponse,
} from "./schema";
