// Generated by dtolator --from-openapi test-multipart.json --zod --angular
// Do not modify manually

import {
  FileInfoSchema,
  MultiUploadResponseSchema,
  ProfileResponseSchema,
  ProfileUploadRequestSchema,
  UpdateProjectFilesDtoSchema,
  UploadMultipleDocumentsDtoSchema,
  UploadResponseSchema,
  UploadUserAvatarDtoSchema,
} from "./schema";
import type {
  FileInfo,
  MultiUploadResponse,
  ProfileResponse,
  ProfileUploadRequest,
  UpdateProjectFilesDto,
  UploadMultipleDocumentsDto,
  UploadResponse,
  UploadUserAvatarDto,
} from "./schema";

export {
  FileInfoSchema,
  MultiUploadResponseSchema,
  ProfileResponseSchema,
  ProfileUploadRequestSchema,
  UpdateProjectFilesDtoSchema,
  UploadMultipleDocumentsDtoSchema,
  UploadResponseSchema,
  UploadUserAvatarDtoSchema,
} from "./schema";
export type {
  FileInfo,
  MultiUploadResponse,
  ProfileResponse,
  ProfileUploadRequest,
  UpdateProjectFilesDto,
  UploadMultipleDocumentsDto,
  UploadResponse,
  UploadUserAvatarDto,
} from "./schema";
