// Generated by dtolator --from-openapi test-multipart.json --zod --angular
// Do not modify manually

import { z } from "zod";
export const FileInfoSchema = z.object({
  id: z.string(),
  filename: z.string(),
  size: z.number().int().describe("File size in bytes"),
  mimeType: z.string().optional(),
  uploadedAt: z.iso.datetime({ offset: true }),
  url: z.url().optional(),
});

export type FileInfo = z.infer<typeof FileInfoSchema>;

export const ProfileResponseSchema = z.object({
  success: z.boolean(),
  profileId: z.guid(),
  photoUrl: z.url().optional(),
  resumeUrl: z.url().nullable().optional(),
  message: z.string().optional(),
});

export type ProfileResponse = z.infer<typeof ProfileResponseSchema>;

export const ProfileUploadRequestSchema = z.object({
  email: z.email(),
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  photo: z.instanceof(File).describe("Profile photo"),
  dateOfBirth: z.iso.date().optional(),
  phoneNumber: z.string().regex(/^\\+?[1-9]\\d{1,14}$/).optional(),
  bio: z.string().max(500).optional(),
  resume: z.instanceof(File).optional().describe("Optional resume file"),
});

export type ProfileUploadRequest = z.infer<typeof ProfileUploadRequestSchema>;

export const UpdateProjectFilesDtoSchema = z.object({
  name: z.string().min(1).max(100).describe("Project name"),
  thumbnail: z.instanceof(File).optional().describe("Project thumbnail image"),
  attachments: z.array(z.instanceof(File)).optional().describe("Additional project files"),
  metadata: z.object({}).optional().describe("Additional metadata as JSON"),
});

export type UpdateProjectFilesDto = z.infer<typeof UpdateProjectFilesDtoSchema>;

export const UploadMultipleDocumentsDtoSchema = z.object({
  files: z.array(z.instanceof(File)).describe("Array of document files"),
  category: z.enum(["invoice", "contract", "report", "other"]).describe("Document category"),
  tags: z.array(z.string()).optional().describe("Tags for organizing documents"),
  isPublic: z.boolean().optional().describe("Whether the documents are publicly accessible"),
});

export type UploadMultipleDocumentsDto = z.infer<typeof UploadMultipleDocumentsDtoSchema>;

export const UploadResponseSchema = z.object({
  success: z.boolean(),
  fileId: z.string().describe("Unique identifier for the uploaded file"),
  url: z.url().optional().describe("URL to access the uploaded file"),
  message: z.string().optional(),
});

export type UploadResponse = z.infer<typeof UploadResponseSchema>;

export const UploadUserAvatarDtoSchema = z.object({
  file: z.instanceof(File).describe("Avatar image file"),
  userId: z.number().int().describe("ID of the user"),
  description: z.string().max(200).optional().describe("Optional description for the avatar"),
});

export type UploadUserAvatarDto = z.infer<typeof UploadUserAvatarDtoSchema>;

export const MultiUploadResponseSchema = z.object({
  success: z.boolean(),
  uploadedCount: z.number().min(0).int(),
  fileIds: z.array(z.string()).optional(),
  files: z.array(FileInfoSchema).optional(),
  message: z.string().optional(),
});

export type MultiUploadResponse = z.infer<typeof MultiUploadResponseSchema>;
