// Generated by dtolator --from-openapi test-multipart.json --zod --angular
// Do not modify manually

import { z } from "zod";
export const FileInfoSchema = z.object({
  id: z.string(),
  filename: z.string(),
  /** File size in bytes */
  size: z.number().int(),
  mimeType: z.string().optional(),
  uploadedAt: z.iso.datetime({ offset: true }),
  url: z.url().optional(),
});

export type FileInfo = z.infer<typeof FileInfoSchema>;

export const ProfileResponseSchema = z.object({
  success: z.boolean(),
  profileId: z.guid(),
  photoUrl: z.url().optional(),
  resumeUrl: z.url().nullable().optional(),
  message: z.string().optional(),
});

export type ProfileResponse = z.infer<typeof ProfileResponseSchema>;

export const ProfileUploadRequestSchema = z.object({
  email: z.email(),
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  /** Profile photo */
  photo: z.instanceof(File),
  dateOfBirth: z.iso.date().optional(),
  phoneNumber: z.string().regex(/^\\+?[1-9]\\d{1,14}$/).optional(),
  bio: z.string().max(500).optional(),
  /** Optional resume file */
  resume: z.instanceof(File).optional(),
});

export type ProfileUploadRequest = z.infer<typeof ProfileUploadRequestSchema>;

export const UpdateProjectFilesDtoSchema = z.object({
  /** Project name */
  name: z.string().min(1).max(100),
  /** Project thumbnail image */
  thumbnail: z.instanceof(File).optional(),
  /** Additional project files */
  attachments: z.array(z.instanceof(File)).optional(),
  /** Additional metadata as JSON */
  metadata: z.object({}).optional(),
});

export type UpdateProjectFilesDto = z.infer<typeof UpdateProjectFilesDtoSchema>;

export const UploadMultipleDocumentsDtoSchema = z.object({
  /** Array of document files */
  files: z.array(z.instanceof(File)),
  /** Document category */
  category: z.enum(["invoice", "contract", "report", "other"]),
  /** Tags for organizing documents */
  tags: z.array(z.string()).optional(),
  /** Whether the documents are publicly accessible */
  isPublic: z.boolean().optional(),
});

export type UploadMultipleDocumentsDto = z.infer<typeof UploadMultipleDocumentsDtoSchema>;

export const UploadResponseSchema = z.object({
  success: z.boolean(),
  /** Unique identifier for the uploaded file */
  fileId: z.string(),
  /** URL to access the uploaded file */
  url: z.url().optional(),
  message: z.string().optional(),
});

export type UploadResponse = z.infer<typeof UploadResponseSchema>;

export const UploadUserAvatarDtoSchema = z.object({
  /** Avatar image file */
  file: z.instanceof(File),
  /** ID of the user */
  userId: z.number().int(),
  /** Optional description for the avatar */
  description: z.string().max(200).optional(),
});

export type UploadUserAvatarDto = z.infer<typeof UploadUserAvatarDtoSchema>;

export const MultiUploadResponseSchema = z.object({
  success: z.boolean(),
  uploadedCount: z.number().min(0).int(),
  fileIds: z.array(z.string()).optional(),
  files: z.array(FileInfoSchema).optional(),
  message: z.string().optional(),
});

export type MultiUploadResponse = z.infer<typeof MultiUploadResponseSchema>;
