// Generated by dtolator --from-json test-data-simple.json --typescript
// Do not modify manually

export interface Root {
  id: number;
  name: string;
  email: string;
  isActive: boolean;
  age: number;
  address: RootAddress;
  tags: string[];
  profile: Profile;
}

export interface Profile {
  bio: string;
  avatar: unknown | null;
  socialLinks: ProfileSocialLinks;
}

export interface ProfileSocialLinks {
  github: string;
  twitter: string;
}

export interface RootAddress {
  street: string;
  city: string;
  zipCode: string;
}
