// Generated by dtolator --from-json test-data-simple.json --typescript
// Do not modify manually

export interface ProfileSocialLinks {
  github: string;
  twitter: string;
}

export interface RootAddress {
  city: string;
  street: string;
  zipCode: string;
}

export interface Profile {
  avatar: unknown | null;
  bio: string;
  socialLinks: ProfileSocialLinks;
}

export interface Root {
  address: RootAddress;
  age: number;
  email: string;
  id: number;
  isActive: boolean;
  name: string;
  profile: Profile;
  tags: string[];
}
