# Generated by dtolator --from-openapi simple-sample.json --python-dict
# Do not modify manually

from typing import TypedDict, Literal, Any
from enum import Enum
from datetime import datetime

class AddressRequired(TypedDict):
    street: str
    city: str
    country: str


class Address(AddressRequired, total=False):
    state: str | None
    postalCode: str | None

class UserProfileRequired(TypedDict):
    firstName: str
    lastName: str


class UserProfile(UserProfileRequired, total=False):
    phoneNumber: str | None
    avatar: str | None
    bio: str | None

class UserRequired(TypedDict):
    id: int
    email: str
    name: str


class User(UserRequired, total=False):
    age: int
    isActive: bool
    tags: list[str]
    status: Literal["active", "inactive", "pending"]
    profile: UserProfile
    address: Address

class ApiResponseRequired(TypedDict):
    success: bool


class ApiResponse(ApiResponseRequired, total=False):
    message: str
    data: User

class CreateUserRequestRequired(TypedDict):
    email: str
    name: str
    profile: UserProfile


class CreateUserRequest(CreateUserRequestRequired, total=False):
    age: int | None
    address: Address

