// Generated by dtolator --from-openapi test-multipart.json --typescript
// Do not modify manually

export interface FileInfo {
  id: string;
  filename: string;
  size: number;
  mimeType?: string;
  uploadedAt: string;
  url?: string;
}

export interface ProfileResponse {
  success: boolean;
  profileId: string;
  photoUrl?: string;
  resumeUrl?: string | null;
  message?: string;
}

export interface ProfileUploadRequest {
  email: string;
  firstName: string;
  lastName: string;
  photo: string;
  dateOfBirth?: string;
  phoneNumber?: string;
  bio?: string;
  resume?: string;
}

export interface UpdateProjectFilesDto {
  name: string;
  thumbnail?: string;
  attachments?: string[];
  metadata?: Record<string, unknown>;
}

export interface UploadMultipleDocumentsDto {
  files: string[];
  category: "invoice" | "contract" | "report" | "other";
  tags?: string[];
  isPublic?: boolean;
}

export interface UploadResponse {
  success: boolean;
  fileId: string;
  url?: string;
  message?: string;
}

export interface UploadUserAvatarDto {
  file: string;
  userId: number;
  description?: string;
}

export interface MultiUploadResponse {
  success: boolean;
  uploadedCount: number;
  fileIds?: string[];
  files?: FileInfo[];
  message?: string;
}
