// Generated by dtolator --from-openapi test-enum-styles.json --zod --ts-enum-style enum
// Do not modify manually

import { z } from "zod";
/** Lifecycle status of an item */
export enum ItemStatus {
  Draft = "draft",
  Active = "active",
  Archived = "archived",
}

export const ItemStatusSchema = z.enum(ItemStatus);

export const NullableColorSchema = z.enum(["red", "green"]).nullable();

export type NullableColor = z.infer<typeof NullableColorSchema>;

export enum Priority {
  ValueNeg1 = -1,
  Value0 = 0,
  Value1 = 1,
  Value2 = 2,
}

export const PrioritySchema = z.enum(Priority);

export enum TrickyNames {
  InProgress = "in-progress",
  InProgress_2 = "IN_PROGRESS",
  InProgress_3 = "inProgress",
  _2fa = "2fa",
  Empty = "",
  WithQuotes = "with \"quotes\"",
}

export const TrickyNamesSchema = z.enum(TrickyNames);

export const ItemSchema = z.object({
  id: z.string(),
  status: ItemStatusSchema,
  priority: PrioritySchema.optional(),
  color: NullableColorSchema.optional(),
  inlineKind: z.enum(["a", "b"]).optional(),
});

export type Item = z.infer<typeof ItemSchema>;
