// Generated by dtolator --from-openapi test-enum-styles.json --typescript --ts-enum-style const
// Do not modify manually

/** Lifecycle status of an item */
export const ItemStatus = {
  Draft: "draft",
  Active: "active",
  Archived: "archived",
} as const;
export type ItemStatus = (typeof ItemStatus)[keyof typeof ItemStatus];

export type NullableColor =
  | "red"
  | "green";

export const Priority = {
  ValueNeg1: -1,
  Value0: 0,
  Value1: 1,
  Value2: 2,
} as const;
export type Priority = (typeof Priority)[keyof typeof Priority];

export const TrickyNames = {
  InProgress: "in-progress",
  InProgress_2: "IN_PROGRESS",
  InProgress_3: "inProgress",
  _2fa: "2fa",
  Empty: "",
  WithQuotes: "with \"quotes\"",
} as const;
export type TrickyNames = (typeof TrickyNames)[keyof typeof TrickyNames];

export interface Item {
  id: string;
  status: ItemStatus;
  priority?: Priority;
  color?: NullableColor;
  inlineKind?: "a" | "b";
}
