// Generated by dtolator --from-json test-special-chars.json --typescript
// Do not modify manually

export interface NestedObject {
  "another field": string;
  "child-field": string;
}

export interface UserData {
  "123numeric": string;
  PascalCaseField: string;
  UPPERCASE_FIELD: string;
  camelCaseField: string;
  "display name": string;
  "email@address": string;
  "field with spaces": string;
  "field-with-hyphen": string;
  "field.with.dots": string;
  field_with_underscore: string;
  "first-name": string;
  last_name: string;
  "nested-object": NestedObject;
  special$field: string;
  "user-id": string;
}

export interface Root {
  "user data": UserData;
}
